/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import ConfigData from '../Utils/ConfigData';
/**
 *  ConfigComponent Page Of Wifi test
 */

export class ComponentConfig {
  WH_100_100 = ConfigData.WH_100_100;
  WH_10_100 = ConfigData.WH_10_100;
  WH_20_100 = ConfigData.WH_20_100;
  WH_30_100 = ConfigData.WH_30_100;
  WH_33_100 = ConfigData.WH_33_100;
  WH_35_100 = ConfigData.WH_35_100;
  WH_40_100 = ConfigData.WH_40_100;
  WH_45_100 = ConfigData.WH_45_100;
  WH_50_100 = ConfigData.WH_50_100;
  WH_55_100 = ConfigData.WH_55_100;
  WH_60_100 = ConfigData.WH_60_100;
  WH_70_100 = ConfigData.WH_70_100;
  WH_80_100 = ConfigData.WH_80_100;
  WH_83_100 = ConfigData.WH_83_100;
  WH_90_100 = ConfigData.WH_90_100;
  value_20 = 20;
  font_20 = 20;
  MAX_LINES_1 = 1;
  MAX_LINES_2 = 2;
  MAX_LINES_3 = 3;
  DURATION_TIME = 200;
}

let componentConfig = new ComponentConfig();

export default componentConfig as ComponentConfig;