"OHOS::Wifi::WifiApHalInterface::GetInstance()";
        "OHOS::Wifi::WifiApHalInterface::GetFrequenciesByBand(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, int, std::__h::vector<int, std::__h::allocator<int>>&)";
        "OHOS::Wifi::WifiApHalInterface::RegisterApEvent(OHOS::Wifi::IWifiApMonitorEventCallback, int)";
        "OHOS::Wifi::WifiApHalInterface::SetPowerModel(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, int)";
        "OHOS::Wifi::WifiApHalInterface::GetPowerModel(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, int&)";
        "OHOS::Wifi::WifiApHalInterface::SetWifiCountryCode(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&)";
        "OHOS::Wifi::WifiApHalInterface::SetConnectMacAddr(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&)";
        "OHOS::Wifi::WifiApHalInterface::SetSoftApConfig(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, OHOS::Wifi::HotspotConfig const&, int)";
        "OHOS::Wifi::WifiApHalInterface::SetMaxConnectNum(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, int, int)";
        "OHOS::Wifi::WifiApHalInterface::EnableAp(int)";
        "OHOS::Wifi::WifiApHalInterface::AddBlockByMac(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, int)";
        "OHOS::Wifi::WifiApHalInterface::DelBlockByMac(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, int)";
        "OHOS::Wifi::WifiApHalInterface::DisAssociateSta(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&)";
        "OHOS::Wifi::WifiApHalInterface::SetSoftApBlockList(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, std::__h::vector<std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>>, std::__h::allocator<std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>>>> const&)";
        "OHOS::Wifi::WifiApHalInterface::DisconnectStaByMac(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&, int)";
        "OHOS::Wifi::WifiApHalInterface::GetStationList(std::__h::vector<std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>>, std::__h::allocator<std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>>>>&, int)";
        "OHOS::Wifi::NetworkInterface::IsValidInterfaceName(std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>> const&)";
        "OHOS::Wifi::IfConfig::ExecCommand(std::__h::vector<std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>>, std::__h::allocator<std::__h::basic_string<char, std::__h::char_traits<char>, std::__h::allocator<char>>>> const&)";