/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Condition_Coverage 分片 part07（须在 describe 内调用） */
export function register_condition_part07(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01674
     * @tc.name WF_C_01674_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01674_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01674');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01675
     * @tc.name WF_C_01675_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01675_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01675');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01676
     * @tc.name WF_C_01676_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01676_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01676');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01677
     * @tc.name WF_C_01677_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01677_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01677');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01678
     * @tc.name WF_C_01678_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01678_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01678');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01679
     * @tc.name WF_C_01679_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01679_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01679');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01680
     * @tc.name WF_C_01680_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01680_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01680');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01681
     * @tc.name WF_C_01681_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01681_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01681');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01682
     * @tc.name WF_C_01682_wifi_scan
     * @tc.desc wifi.scan condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01682_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01682');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01683
     * @tc.name WF_C_01683_wifi_scan
     * @tc.desc wifi.scan condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01683_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01683');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01684
     * @tc.name WF_C_01684_wifi_scan
     * @tc.desc wifi.scan condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01684_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01684');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01685
     * @tc.name WF_C_01685_wifi_scan
     * @tc.desc wifi.scan condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01685_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01685');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01686
     * @tc.name WF_C_01686_wifi_scan
     * @tc.desc wifi.scan condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01686_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01686');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01687
     * @tc.name WF_C_01687_wifi_scan
     * @tc.desc wifi.scan condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01687_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01687');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01688
     * @tc.name WF_C_01688_wifi_scan
     * @tc.desc wifi.scan condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01688_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01688');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01689
     * @tc.name WF_C_01689_wifi_scan
     * @tc.desc wifi.scan condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01689_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_C_01689');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01690
     * @tc.name WF_C_01690_wifi_isConnected
     * @tc.desc wifi.isConnected condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01690_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01690');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01691
     * @tc.name WF_C_01691_wifi_isConnected
     * @tc.desc wifi.isConnected condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01691_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01691');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01692
     * @tc.name WF_C_01692_wifi_isConnected
     * @tc.desc wifi.isConnected condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01692_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01692');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01693
     * @tc.name WF_C_01693_wifi_isConnected
     * @tc.desc wifi.isConnected condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01693_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01693');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01694
     * @tc.name WF_C_01694_wifi_isConnected
     * @tc.desc wifi.isConnected condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01694_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01694');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01695
     * @tc.name WF_C_01695_wifi_isConnected
     * @tc.desc wifi.isConnected condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01695_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01695');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01696
     * @tc.name WF_C_01696_wifi_isConnected
     * @tc.desc wifi.isConnected condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01696_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01696');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01697
     * @tc.name WF_C_01697_wifi_isConnected
     * @tc.desc wifi.isConnected condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01697_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_C_01697');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01698
     * @tc.name WF_C_01698_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01698_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01698');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01699
     * @tc.name WF_C_01699_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01699_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01699');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01700
     * @tc.name WF_C_01700_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01700_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01700');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01701
     * @tc.name WF_C_01701_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01701_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01701');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01702
     * @tc.name WF_C_01702_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01702_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01702');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01703
     * @tc.name WF_C_01703_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01703_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01703');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01704
     * @tc.name WF_C_01704_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01704_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01704');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01705
     * @tc.name WF_C_01705_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01705_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_C_01705');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01706
     * @tc.name WF_C_01706_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01706_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01706');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01707
     * @tc.name WF_C_01707_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01707_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01707');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01708
     * @tc.name WF_C_01708_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01708_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01708');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01709
     * @tc.name WF_C_01709_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01709_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01709');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01710
     * @tc.name WF_C_01710_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01710_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01710');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01711
     * @tc.name WF_C_01711_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01711_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01711');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01712
     * @tc.name WF_C_01712_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01712_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01712');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01713
     * @tc.name WF_C_01713_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01713_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_C_01713');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01714
     * @tc.name WF_C_01714_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01714_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01714');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01715
     * @tc.name WF_C_01715_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01715_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01715');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01716
     * @tc.name WF_C_01716_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01716_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01716');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01717
     * @tc.name WF_C_01717_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01717_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01717');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01718
     * @tc.name WF_C_01718_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01718_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01718');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01719
     * @tc.name WF_C_01719_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01719_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01719');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01720
     * @tc.name WF_C_01720_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01720_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01720');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01721
     * @tc.name WF_C_01721_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01721_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_C_01721');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01722
     * @tc.name WF_C_01722_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01722_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01722');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01723
     * @tc.name WF_C_01723_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01723_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01723');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01724
     * @tc.name WF_C_01724_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01724_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01724');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01725
     * @tc.name WF_C_01725_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01725_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01725');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01726
     * @tc.name WF_C_01726_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01726_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01726');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01727
     * @tc.name WF_C_01727_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01727_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01727');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01728
     * @tc.name WF_C_01728_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01728_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01728');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01729
     * @tc.name WF_C_01729_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01729_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_C_01729');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01730
     * @tc.name WF_C_01730_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01730_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01730');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01731
     * @tc.name WF_C_01731_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01731_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01731');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01732
     * @tc.name WF_C_01732_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01732_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01732');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01733
     * @tc.name WF_C_01733_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01733_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01733');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01734
     * @tc.name WF_C_01734_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01734_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01734');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01735
     * @tc.name WF_C_01735_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01735_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01735');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01736
     * @tc.name WF_C_01736_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01736_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01736');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01737
     * @tc.name WF_C_01737_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01737_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_C_01737');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01738
     * @tc.name WF_C_01738_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01738_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01738');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01739
     * @tc.name WF_C_01739_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01739_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01739');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01740
     * @tc.name WF_C_01740_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01740_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01740');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01741
     * @tc.name WF_C_01741_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01741_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01741');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01742
     * @tc.name WF_C_01742_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01742_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01742');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01743
     * @tc.name WF_C_01743_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01743_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01743');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01744
     * @tc.name WF_C_01744_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01744_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01744');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01745
     * @tc.name WF_C_01745_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01745_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01745');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01746
     * @tc.name WF_C_01746_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01746_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01746');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01747
     * @tc.name WF_C_01747_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01747_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01747');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01748
     * @tc.name WF_C_01748_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01748_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01748');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01749
     * @tc.name WF_C_01749_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01749_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01749');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01750
     * @tc.name WF_C_01750_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01750_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01750');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01751
     * @tc.name WF_C_01751_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01751_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01751');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01752
     * @tc.name WF_C_01752_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01752_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01752');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01753
     * @tc.name WF_C_01753_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01753_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_C_01753');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01754
     * @tc.name WF_C_01754_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01754_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01754');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01755
     * @tc.name WF_C_01755_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01755_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01755');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01756
     * @tc.name WF_C_01756_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01756_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01756');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01757
     * @tc.name WF_C_01757_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01757_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01757');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01758
     * @tc.name WF_C_01758_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01758_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01758');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01759
     * @tc.name WF_C_01759_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01759_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01759');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01760
     * @tc.name WF_C_01760_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01760_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01760');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01761
     * @tc.name WF_C_01761_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01761_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_C_01761');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01762
     * @tc.name WF_C_01762_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01762_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01762');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01763
     * @tc.name WF_C_01763_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01763_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01763');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01764
     * @tc.name WF_C_01764_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01764_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01764');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01765
     * @tc.name WF_C_01765_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01765_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01765');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01766
     * @tc.name WF_C_01766_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01766_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01766');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01767
     * @tc.name WF_C_01767_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01767_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01767');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01768
     * @tc.name WF_C_01768_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01768_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01768');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01769
     * @tc.name WF_C_01769_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01769_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_C_01769');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01770
     * @tc.name WF_C_01770_wifi_getP2pPeerDevices
     * @tc.desc wifi.getP2pPeerDevices condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01770_wifi_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WF_C_01770');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01771
     * @tc.name WF_C_01771_wifi_getP2pPeerDevices
     * @tc.desc wifi.getP2pPeerDevices condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01771_wifi_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WF_C_01771');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01772
     * @tc.name WF_C_01772_wifi_getP2pPeerDevices
     * @tc.desc wifi.getP2pPeerDevices condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01772_wifi_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WF_C_01772');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_C_01773
     * @tc.name WF_C_01773_wifi_getP2pPeerDevices
     * @tc.desc wifi.getP2pPeerDevices condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WF_C_01773_wifi_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WF_C_01773');
    });

}
