/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Parameter_Coverage 分片 part03（须在 describe 内调用） */
export function register_param_part03(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01039
     * @tc.name WM_DC_01039_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=0 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01039_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01039');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01040
     * @tc.name WM_DC_01040_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=0 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01040_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01040');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01041
     * @tc.name WM_DC_01041_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=0 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01041_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01041');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01042
     * @tc.name WM_DC_01042_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=1 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01042_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01042');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01043
     * @tc.name WM_DC_01043_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=1 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01043_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01043');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01044
     * @tc.name WM_DC_01044_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=1 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01044_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01044');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01045
     * @tc.name WM_DC_01045_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=1 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01045_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01045');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01046
     * @tc.name WM_DC_01046_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=1 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01046_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01046');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01047
     * @tc.name WM_DC_01047_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=1 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01047_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01047');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01048
     * @tc.name WM_DC_01048_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=2 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01048_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01048');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01049
     * @tc.name WM_DC_01049_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=2 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01049_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01049');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01050
     * @tc.name WM_DC_01050_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=2 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01050_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01050');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01051
     * @tc.name WM_DC_01051_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=2 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01051_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01051');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01052
     * @tc.name WM_DC_01052_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=2 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01052_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01052');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01053
     * @tc.name WM_DC_01053_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=2 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01053_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01053');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01054
     * @tc.name WM_DC_01054_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=3 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01054_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01054');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01055
     * @tc.name WM_DC_01055_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=3 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01055_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01055');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01056
     * @tc.name WM_DC_01056_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=3 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01056_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01056');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01057
     * @tc.name WM_DC_01057_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=3 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01057_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01057');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01058
     * @tc.name WM_DC_01058_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=3 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01058_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01058');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01059
     * @tc.name WM_DC_01059_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=3 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01059_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01059');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01060
     * @tc.name WM_DC_01060_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=4 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01060_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01060');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01061
     * @tc.name WM_DC_01061_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=4 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01061_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01061');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01062
     * @tc.name WM_DC_01062_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=4 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01062_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01062');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01063
     * @tc.name WM_DC_01063_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=4 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01063_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01063');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01064
     * @tc.name WM_DC_01064_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=4 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01064_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01064');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01065
     * @tc.name WM_DC_01065_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=4 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01065_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01065');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01066
     * @tc.name WM_DC_01066_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=5 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01066_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01066');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01067
     * @tc.name WM_DC_01067_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=5 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01067_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01067');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01068
     * @tc.name WM_DC_01068_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=5 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01068_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01068');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01069
     * @tc.name WM_DC_01069_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=5 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01069_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01069');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01070
     * @tc.name WM_DC_01070_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=5 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01070_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01070');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01071
     * @tc.name WM_DC_01071_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=5 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01071_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01071');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01072
     * @tc.name WM_DC_01072_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=6 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01072_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01072');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01073
     * @tc.name WM_DC_01073_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=6 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01073_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01073');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01074
     * @tc.name WM_DC_01074_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=6 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01074_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01074');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01075
     * @tc.name WM_DC_01075_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=6 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01075_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01075');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01076
     * @tc.name WM_DC_01076_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=6 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01076_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01076');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01077
     * @tc.name WM_DC_01077_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=6 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01077_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01077');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01078
     * @tc.name WM_DC_01078_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=7 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01078_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01078');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01079
     * @tc.name WM_DC_01079_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=7 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01079_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01079');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01080
     * @tc.name WM_DC_01080_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=7 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01080_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01080');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01081
     * @tc.name WM_DC_01081_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=7 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01081_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01081');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01082
     * @tc.name WM_DC_01082_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=7 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01082_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01082');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01083
     * @tc.name WM_DC_01083_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=7 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01083_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01083');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01084
     * @tc.name WM_DC_01084_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=8 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01084_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01084');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01085
     * @tc.name WM_DC_01085_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=8 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01085_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01085');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01086
     * @tc.name WM_DC_01086_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=8 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01086_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01086');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01087
     * @tc.name WM_DC_01087_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=8 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01087_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01087');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01088
     * @tc.name WM_DC_01088_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=8 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01088_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01088');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01089
     * @tc.name WM_DC_01089_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=8 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01089_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01089');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01090
     * @tc.name WM_DC_01090_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=9 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01090_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01090');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01091
     * @tc.name WM_DC_01091_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=9 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01091_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01091');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01092
     * @tc.name WM_DC_01092_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=9 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01092_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01092');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01093
     * @tc.name WM_DC_01093_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=9 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01093_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01093');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01094
     * @tc.name WM_DC_01094_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=9 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01094_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01094');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01095
     * @tc.name WM_DC_01095_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=1 sec=9 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01095_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01095');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01096
     * @tc.name WM_DC_01096_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=0 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01096_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01096');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01097
     * @tc.name WM_DC_01097_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=0 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01097_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01097');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01098
     * @tc.name WM_DC_01098_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=0 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01098_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01098');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01099
     * @tc.name WM_DC_01099_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=0 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01099_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01099');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01100
     * @tc.name WM_DC_01100_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=0 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01100_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01100');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01101
     * @tc.name WM_DC_01101_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=0 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01101_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01101');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01102
     * @tc.name WM_DC_01102_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=1 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01102_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01102');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01103
     * @tc.name WM_DC_01103_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=1 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01103_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01103');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01104
     * @tc.name WM_DC_01104_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=1 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01104_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01104');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01105
     * @tc.name WM_DC_01105_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=1 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01105_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01105');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01106
     * @tc.name WM_DC_01106_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=1 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01106_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01106');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01107
     * @tc.name WM_DC_01107_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=1 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01107_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01107');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01108
     * @tc.name WM_DC_01108_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=2 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01108_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01108');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01109
     * @tc.name WM_DC_01109_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=2 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01109_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01109');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01110
     * @tc.name WM_DC_01110_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=2 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01110_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01110');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01111
     * @tc.name WM_DC_01111_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=2 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01111_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01111');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01112
     * @tc.name WM_DC_01112_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=2 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01112_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01112');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01113
     * @tc.name WM_DC_01113_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=2 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01113_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01113');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01114
     * @tc.name WM_DC_01114_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=3 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01114_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01114');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01115
     * @tc.name WM_DC_01115_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=3 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01115_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01115');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01116
     * @tc.name WM_DC_01116_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=3 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01116_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01116');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01117
     * @tc.name WM_DC_01117_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=3 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01117_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01117');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01118
     * @tc.name WM_DC_01118_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=3 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01118_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01118');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01119
     * @tc.name WM_DC_01119_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=3 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01119_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01119');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01120
     * @tc.name WM_DC_01120_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=4 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01120_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01120');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01121
     * @tc.name WM_DC_01121_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=4 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01121_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01121');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01122
     * @tc.name WM_DC_01122_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=4 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01122_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01122');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01123
     * @tc.name WM_DC_01123_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=4 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01123_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01123');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01124
     * @tc.name WM_DC_01124_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=4 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01124_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01124');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01125
     * @tc.name WM_DC_01125_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=4 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01125_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01125');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01126
     * @tc.name WM_DC_01126_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=5 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01126_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01126');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01127
     * @tc.name WM_DC_01127_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=5 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01127_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01127');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01128
     * @tc.name WM_DC_01128_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=5 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01128_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01128');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01129
     * @tc.name WM_DC_01129_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=5 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01129_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01129');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01130
     * @tc.name WM_DC_01130_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=5 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01130_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01130');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01131
     * @tc.name WM_DC_01131_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=5 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01131_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01131');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01132
     * @tc.name WM_DC_01132_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=6 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01132_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01132');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01133
     * @tc.name WM_DC_01133_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=6 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01133_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01133');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01134
     * @tc.name WM_DC_01134_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=6 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01134_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01134');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01135
     * @tc.name WM_DC_01135_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=6 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01135_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01135');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01136
     * @tc.name WM_DC_01136_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=6 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01136_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01136');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01137
     * @tc.name WM_DC_01137_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=6 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01137_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01137');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01138
     * @tc.name WM_DC_01138_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=7 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01138_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01138');
    });

}
