/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Condition_Coverage 分片 part03（须在 describe 内调用） */
export function register_condition_part03(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00536
     * @tc.name WM_C_00536_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00536_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00536');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00537
     * @tc.name WM_C_00537_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00537_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00537');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00538
     * @tc.name WM_C_00538_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00538_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00538');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00539
     * @tc.name WM_C_00539_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00539_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00539');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00540
     * @tc.name WM_C_00540_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00540_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00540');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00541
     * @tc.name WM_C_00541_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00541_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00541');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00542
     * @tc.name WM_C_00542_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00542_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00542');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00543
     * @tc.name WM_C_00543_wifiManager_reconnect
     * @tc.desc wifiManager.reconnect condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00543_wifiManager_reconnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00543');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00544
     * @tc.name WM_C_00544_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00544_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00544');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00545
     * @tc.name WM_C_00545_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00545_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00545');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00546
     * @tc.name WM_C_00546_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00546_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00546');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00547
     * @tc.name WM_C_00547_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00547_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00547');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00548
     * @tc.name WM_C_00548_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00548_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00548');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00549
     * @tc.name WM_C_00549_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00549_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00549');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00550
     * @tc.name WM_C_00550_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00550_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00550');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00551
     * @tc.name WM_C_00551_wifiManager_getDeviceConfigs
     * @tc.desc wifiManager.getDeviceConfigs condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00551_wifiManager_getDeviceConfigs', 0, async () => {
      await executeApiTestCaseById('WM_C_00551');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00552
     * @tc.name WM_C_00552_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00552_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00552');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00553
     * @tc.name WM_C_00553_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00553_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00553');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00554
     * @tc.name WM_C_00554_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00554_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00554');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00555
     * @tc.name WM_C_00555_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00555_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00555');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00556
     * @tc.name WM_C_00556_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00556_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00556');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00557
     * @tc.name WM_C_00557_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00557_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00557');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00558
     * @tc.name WM_C_00558_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00558_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00558');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00559
     * @tc.name WM_C_00559_wifiManager_allowAutoConnect
     * @tc.desc wifiManager.allowAutoConnect condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00559_wifiManager_allowAutoConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00559');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00560
     * @tc.name WM_C_00560_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00560_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00560');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00561
     * @tc.name WM_C_00561_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00561_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00561');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00562
     * @tc.name WM_C_00562_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00562_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00562');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00563
     * @tc.name WM_C_00563_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00563_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00563');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00564
     * @tc.name WM_C_00564_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00564_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00564');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00565
     * @tc.name WM_C_00565_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00565_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00565');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00566
     * @tc.name WM_C_00566_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00566_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00566');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00567
     * @tc.name WM_C_00567_wifiManager_disableNetwork
     * @tc.desc wifiManager.disableNetwork condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00567_wifiManager_disableNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00567');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00568
     * @tc.name WM_C_00568_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00568_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00568');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00569
     * @tc.name WM_C_00569_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00569_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00569');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00570
     * @tc.name WM_C_00570_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00570_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00570');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00571
     * @tc.name WM_C_00571_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00571_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00571');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00572
     * @tc.name WM_C_00572_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00572_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00572');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00573
     * @tc.name WM_C_00573_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00573_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00573');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00574
     * @tc.name WM_C_00574_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00574_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00574');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00575
     * @tc.name WM_C_00575_wifiManager_removeAllNetwork
     * @tc.desc wifiManager.removeAllNetwork condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00575_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_C_00575');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00576
     * @tc.name WM_C_00576_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00576_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00576');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00577
     * @tc.name WM_C_00577_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00577_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00577');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00578
     * @tc.name WM_C_00578_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00578_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00578');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00579
     * @tc.name WM_C_00579_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00579_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00579');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00580
     * @tc.name WM_C_00580_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00580_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00580');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00581
     * @tc.name WM_C_00581_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00581_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00581');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00582
     * @tc.name WM_C_00582_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00582_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00582');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00583
     * @tc.name WM_C_00583_wifiManager_removeDevice
     * @tc.desc wifiManager.removeDevice condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00583_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00583');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00584
     * @tc.name WM_C_00584_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00584_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00584');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00585
     * @tc.name WM_C_00585_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00585_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00585');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00586
     * @tc.name WM_C_00586_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00586_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00586');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00587
     * @tc.name WM_C_00587_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00587_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00587');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00588
     * @tc.name WM_C_00588_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00588_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00588');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00589
     * @tc.name WM_C_00589_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00589_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00589');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00590
     * @tc.name WM_C_00590_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00590_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00590');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00591
     * @tc.name WM_C_00591_wifiManager_isBandTypeSupported
     * @tc.desc wifiManager.isBandTypeSupported condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00591_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00591');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00592
     * @tc.name WM_C_00592_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00592_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00592');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00593
     * @tc.name WM_C_00593_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00593_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00593');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00594
     * @tc.name WM_C_00594_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00594_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00594');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00595
     * @tc.name WM_C_00595_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00595_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00595');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00596
     * @tc.name WM_C_00596_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00596_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00596');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00597
     * @tc.name WM_C_00597_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00597_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00597');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00598
     * @tc.name WM_C_00598_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00598_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00598');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00599
     * @tc.name WM_C_00599_wifiManager_get5GChannelList
     * @tc.desc wifiManager.get5GChannelList condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00599_wifiManager_get5GChannelList', 0, async () => {
      await executeApiTestCaseById('WM_C_00599');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00600
     * @tc.name WM_C_00600_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00600_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00600');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00601
     * @tc.name WM_C_00601_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00601_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00601');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00602
     * @tc.name WM_C_00602_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00602_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00602');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00603
     * @tc.name WM_C_00603_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00603_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00603');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00604
     * @tc.name WM_C_00604_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00604_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00604');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00605
     * @tc.name WM_C_00605_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00605_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00605');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00606
     * @tc.name WM_C_00606_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00606_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00606');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00607
     * @tc.name WM_C_00607_wifiManager_getDisconnectedReason
     * @tc.desc wifiManager.getDisconnectedReason condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00607_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_C_00607');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00608
     * @tc.name WM_C_00608_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00608_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00608');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00609
     * @tc.name WM_C_00609_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00609_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00609');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00610
     * @tc.name WM_C_00610_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00610_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00610');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00611
     * @tc.name WM_C_00611_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00611_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00611');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00612
     * @tc.name WM_C_00612_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00612_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00612');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00613
     * @tc.name WM_C_00613_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00613_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00613');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00614
     * @tc.name WM_C_00614_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00614_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00614');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00615
     * @tc.name WM_C_00615_wifiManager_startPortalCertification
     * @tc.desc wifiManager.startPortalCertification condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00615_wifiManager_startPortalCertification', 0, async () => {
      await executeApiTestCaseById('WM_C_00615');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00616
     * @tc.name WM_C_00616_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00616_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00616');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00617
     * @tc.name WM_C_00617_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00617_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00617');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00618
     * @tc.name WM_C_00618_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00618_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00618');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00619
     * @tc.name WM_C_00619_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00619_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00619');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00620
     * @tc.name WM_C_00620_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00620_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00620');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00621
     * @tc.name WM_C_00621_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00621_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00621');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00622
     * @tc.name WM_C_00622_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00622_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00622');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00623
     * @tc.name WM_C_00623_wifiManager_startWifiDetection
     * @tc.desc wifiManager.startWifiDetection condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00623_wifiManager_startWifiDetection', 0, async () => {
      await executeApiTestCaseById('WM_C_00623');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00624
     * @tc.name WM_C_00624_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00624_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00624');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00625
     * @tc.name WM_C_00625_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00625_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00625');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00626
     * @tc.name WM_C_00626_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00626_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00626');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00627
     * @tc.name WM_C_00627_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00627_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00627');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00628
     * @tc.name WM_C_00628_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00628_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00628');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00629
     * @tc.name WM_C_00629_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00629_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00629');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00630
     * @tc.name WM_C_00630_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00630_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00630');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00631
     * @tc.name WM_C_00631_wifiManager_isRandomMacDisabled
     * @tc.desc wifiManager.isRandomMacDisabled condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00631_wifiManager_isRandomMacDisabled', 0, async () => {
      await executeApiTestCaseById('WM_C_00631');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00632
     * @tc.name WM_C_00632_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00632_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00632');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00633
     * @tc.name WM_C_00633_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00633_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00633');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00634
     * @tc.name WM_C_00634_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00634_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00634');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00635
     * @tc.name WM_C_00635_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00635_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00635');
    });

}
