/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Parameter_Coverage 分片 part06（须在 describe 内调用） */
export function register_param_part06(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01459
     * @tc.name WM_X_01459_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=3 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01459_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01459');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01460
     * @tc.name WM_X_01460_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=4 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01460_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01460');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01461
     * @tc.name WM_X_01461_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=4 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01461_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01461');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01462
     * @tc.name WM_X_01462_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=4 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01462_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01462');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01463
     * @tc.name WM_X_01463_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=5 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01463_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01463');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01464
     * @tc.name WM_X_01464_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=5 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01464_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01464');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01465
     * @tc.name WM_X_01465_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=5 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01465_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01465');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01466
     * @tc.name WM_X_01466_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=6 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01466_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01466');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01467
     * @tc.name WM_X_01467_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=6 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01467_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01467');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01468
     * @tc.name WM_X_01468_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=6 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01468_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01468');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01469
     * @tc.name WM_X_01469_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=7 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01469_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01469');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01470
     * @tc.name WM_X_01470_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=7 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01470_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01470');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01471
     * @tc.name WM_X_01471_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=7 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01471_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01471');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01472
     * @tc.name WM_X_01472_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=8 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01472_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01472');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01473
     * @tc.name WM_X_01473_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=8 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01473_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01473');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01474
     * @tc.name WM_X_01474_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=8 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01474_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01474');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01475
     * @tc.name WM_X_01475_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=9 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01475_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01475');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01476
     * @tc.name WM_X_01476_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=9 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01476_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01476');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01477
     * @tc.name WM_X_01477_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=9 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01477_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01477');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01478
     * @tc.name WM_X_01478_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_a sec=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01478_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01478');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01479
     * @tc.name WM_X_01479_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_a sec=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01479_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01479');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01480
     * @tc.name WM_X_01480_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_a sec=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01480_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01480');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01481
     * @tc.name WM_X_01481_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_a sec=3
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01481_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01481');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01482
     * @tc.name WM_X_01482_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_a sec=4
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01482_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01482');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01483
     * @tc.name WM_X_01483_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_b sec=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01483_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01483');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01484
     * @tc.name WM_X_01484_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_b sec=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01484_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01484');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01485
     * @tc.name WM_X_01485_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_b sec=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01485_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01485');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01486
     * @tc.name WM_X_01486_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_b sec=3
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01486_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01486');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01487
     * @tc.name WM_X_01487_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_b sec=4
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01487_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01487');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01488
     * @tc.name WM_X_01488_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_c sec=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01488_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01488');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01489
     * @tc.name WM_X_01489_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_c sec=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01489_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01489');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01490
     * @tc.name WM_X_01490_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_c sec=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01490_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01490');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01491
     * @tc.name WM_X_01491_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_c sec=3
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01491_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01491');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01492
     * @tc.name WM_X_01492_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_c sec=4
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01492_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01492');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01493
     * @tc.name WM_X_01493_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_d sec=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01493_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01493');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01494
     * @tc.name WM_X_01494_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_d sec=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01494_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01494');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01495
     * @tc.name WM_X_01495_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_d sec=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01495_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01495');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01496
     * @tc.name WM_X_01496_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_d sec=3
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01496_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01496');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01497
     * @tc.name WM_X_01497_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_d sec=4
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01497_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01497');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01498
     * @tc.name WM_X_01498_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_e sec=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01498_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01498');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01499
     * @tc.name WM_X_01499_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_e sec=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01499_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01499');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01500
     * @tc.name WM_X_01500_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_e sec=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01500_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01500');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01501
     * @tc.name WM_X_01501_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_e sec=3
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01501_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01501');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01502
     * @tc.name WM_X_01502_wifiManager_connectToDevice
     * @tc.desc connectToDevice ssid=ut_conn_e sec=4
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01502_wifiManager_connectToDevice', 0, async () => {
      await executeApiTestCaseById('WM_X_01502');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01503
     * @tc.name WM_X_01503_wifiManager_connectToCandidateConfig
     * @tc.desc connectToCandidateConfig netId=-1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01503_wifiManager_connectToCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_X_01503');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01504
     * @tc.name WM_X_01504_wifiManager_connectToCandidateConfig
     * @tc.desc connectToCandidateConfig netId=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01504_wifiManager_connectToCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_X_01504');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01505
     * @tc.name WM_X_01505_wifiManager_connectToCandidateConfig
     * @tc.desc connectToCandidateConfig netId=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01505_wifiManager_connectToCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_X_01505');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01506
     * @tc.name WM_X_01506_wifiManager_connectToCandidateConfig
     * @tc.desc connectToCandidateConfig netId=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01506_wifiManager_connectToCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_X_01506');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01507
     * @tc.name WM_X_01507_wifiManager_connectToCandidateConfig
     * @tc.desc connectToCandidateConfig netId=3
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01507_wifiManager_connectToCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_X_01507');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01539
     * @tc.name WM_X_01539_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01539_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01539');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01540
     * @tc.name WM_X_01540_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01540_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01540');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01541
     * @tc.name WM_X_01541_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01541_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01541');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01542
     * @tc.name WM_X_01542_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=3
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01542_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01542');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01543
     * @tc.name WM_X_01543_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=4
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01543_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01543');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01544
     * @tc.name WM_X_01544_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=5
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01544_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01544');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01545
     * @tc.name WM_X_01545_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=6
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01545_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01545');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01546
     * @tc.name WM_X_01546_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=7
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01546_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01546');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01547
     * @tc.name WM_X_01547_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=8
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01547_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01547');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01548
     * @tc.name WM_X_01548_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=9
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01548_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01548');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01549
     * @tc.name WM_X_01549_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=10
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01549_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01549');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01550
     * @tc.name WM_X_01550_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=11
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01550_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01550');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01551
     * @tc.name WM_X_01551_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=12
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01551_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01551');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01552
     * @tc.name WM_X_01552_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=13
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01552_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01552');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01553
     * @tc.name WM_X_01553_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=14
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01553_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01553');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01554
     * @tc.name WM_X_01554_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=15
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01554_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01554');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01555
     * @tc.name WM_X_01555_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=16
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01555_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01555');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01556
     * @tc.name WM_X_01556_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=17
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01556_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01556');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01557
     * @tc.name WM_X_01557_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=18
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01557_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01557');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01558
     * @tc.name WM_X_01558_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=19
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01558_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01558');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01559
     * @tc.name WM_X_01559_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=20
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01559_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01559');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01560
     * @tc.name WM_X_01560_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=21
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01560_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01560');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01561
     * @tc.name WM_X_01561_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=22
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01561_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01561');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01562
     * @tc.name WM_X_01562_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=23
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01562_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01562');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01563
     * @tc.name WM_X_01563_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=24
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01563_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01563');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01564
     * @tc.name WM_X_01564_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=25
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01564_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01564');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01565
     * @tc.name WM_X_01565_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=26
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01565_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01565');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01566
     * @tc.name WM_X_01566_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=27
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01566_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01566');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01567
     * @tc.name WM_X_01567_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=28
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01567_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01567');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01568
     * @tc.name WM_X_01568_wifiManager_getSignalLevel
     * @tc.desc getSignalLevel sweep i=29
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01568_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_X_01568');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01569
     * @tc.name WF_P_01569_wifi_enableWifi
     * @tc.desc wifi.enableWifi param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01569_wifi_enableWifi', 0, async () => {
      await executeApiTestCaseById('WF_P_01569');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01570
     * @tc.name WF_P_01570_wifi_disableWifi
     * @tc.desc wifi.disableWifi param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01570_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_P_01570');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01571
     * @tc.name WF_P_01571_wifi_isWifiActive
     * @tc.desc wifi.isWifiActive param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01571_wifi_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WF_P_01571');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01572
     * @tc.name WF_P_01572_wifi_scan
     * @tc.desc wifi.scan param#0 precond=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01572_wifi_scan', 0, async () => {
      await executeApiTestCaseById('WF_P_01572');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01573
     * @tc.name WF_P_01573_wifi_isConnected
     * @tc.desc wifi.isConnected param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01573_wifi_isConnected', 0, async () => {
      await executeApiTestCaseById('WF_P_01573');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01574
     * @tc.name WF_P_01574_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01574_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_P_01574');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01575
     * @tc.name WF_P_01575_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel param#1 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01575_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_P_01575');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01576
     * @tc.name WF_P_01576_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel param#2 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01576_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_P_01576');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01577
     * @tc.name WF_P_01577_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel param#3 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01577_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_P_01577');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01578
     * @tc.name WF_P_01578_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel param#4 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01578_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_P_01578');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01579
     * @tc.name WF_P_01579_wifi_getSignalLevel
     * @tc.desc wifi.getSignalLevel param#5 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01579_wifi_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WF_P_01579');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01580
     * @tc.name WF_P_01580_wifi_getIpInfo
     * @tc.desc wifi.getIpInfo param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01580_wifi_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WF_P_01580');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01581
     * @tc.name WF_P_01581_wifi_getCountryCode
     * @tc.desc wifi.getCountryCode param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01581_wifi_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WF_P_01581');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01582
     * @tc.name WF_P_01582_wifi_getSupportedFeatures
     * @tc.desc wifi.getSupportedFeatures param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01582_wifi_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WF_P_01582');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01583
     * @tc.name WF_P_01583_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01583_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01583');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01584
     * @tc.name WF_P_01584_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#1 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01584_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01584');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01585
     * @tc.name WF_P_01585_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#2 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01585_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01585');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01586
     * @tc.name WF_P_01586_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#3 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01586_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01586');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01587
     * @tc.name WF_P_01587_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#4 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01587_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01587');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01588
     * @tc.name WF_P_01588_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#5 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01588_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01588');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01589
     * @tc.name WF_P_01589_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#6 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01589_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01589');
    });

}
