/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Parameter_Coverage 分片 part05（须在 describe 内调用） */
export function register_param_part05(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01239
     * @tc.name WM_HC_01239_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01239_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01239');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01240
     * @tc.name WM_HC_01240_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=6 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01240_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01240');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01241
     * @tc.name WM_HC_01241_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=6 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01241_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01241');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01242
     * @tc.name WM_HC_01242_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=11 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01242_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01242');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01243
     * @tc.name WM_HC_01243_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=11 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01243_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01243');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01244
     * @tc.name WM_HC_01244_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=36 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01244_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01244');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01245
     * @tc.name WM_HC_01245_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=36 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01245_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01245');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01246
     * @tc.name WM_P2P_01246_wifiManager_createGroup
     * @tc.desc createGroup netId=0 goBand=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01246_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01246');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01247
     * @tc.name WM_P2P_01247_wifiManager_createGroup
     * @tc.desc createGroup netId=0 goBand=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01247_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01247');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01248
     * @tc.name WM_P2P_01248_wifiManager_createGroup
     * @tc.desc createGroup netId=0 goBand=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01248_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01248');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01249
     * @tc.name WM_P2P_01249_wifiManager_createGroup
     * @tc.desc createGroup netId=1 goBand=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01249_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01249');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01250
     * @tc.name WM_P2P_01250_wifiManager_createGroup
     * @tc.desc createGroup netId=1 goBand=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01250_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01250');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01251
     * @tc.name WM_P2P_01251_wifiManager_createGroup
     * @tc.desc createGroup netId=1 goBand=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01251_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01251');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01252
     * @tc.name WM_P2P_01252_wifiManager_createGroup
     * @tc.desc createGroup netId=2 goBand=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01252_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01252');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01253
     * @tc.name WM_P2P_01253_wifiManager_createGroup
     * @tc.desc createGroup netId=2 goBand=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01253_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01253');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01254
     * @tc.name WM_P2P_01254_wifiManager_createGroup
     * @tc.desc createGroup netId=2 goBand=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01254_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01254');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01255
     * @tc.name WM_P2P_01255_wifiManager_createGroup
     * @tc.desc createGroup netId=-1 goBand=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01255_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01255');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01256
     * @tc.name WM_P2P_01256_wifiManager_createGroup
     * @tc.desc createGroup netId=-1 goBand=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01256_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01256');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01257
     * @tc.name WM_P2P_01257_wifiManager_createGroup
     * @tc.desc createGroup netId=-1 goBand=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01257_wifiManager_createGroup', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01257');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01258
     * @tc.name WM_P2P_01258_wifiManager_p2pConnect
     * @tc.desc p2pConnect netId=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01258_wifiManager_p2pConnect', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01258');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01259
     * @tc.name WM_P2P_01259_wifiManager_p2pConnect
     * @tc.desc p2pConnect netId=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01259_wifiManager_p2pConnect', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01259');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01260
     * @tc.name WM_P2P_01260_wifiManager_p2pConnect
     * @tc.desc p2pConnect netId=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01260_wifiManager_p2pConnect', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01260');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_P2P_01261
     * @tc.name WM_P2P_01261_wifiManager_p2pConnect
     * @tc.desc p2pConnect netId=-1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_P2P_01261_wifiManager_p2pConnect', 0, async () => {
      await executeApiTestCaseById('WM_P2P_01261');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01382
     * @tc.name WM_PC_01382_wifiManager_getScanResults
     * @tc.desc getScanResults invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01382_wifiManager_getScanResults', 0, async () => {
      await executeApiTestCaseById('WM_PC_01382');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01383
     * @tc.name WM_PC_01383_wifiManager_getScanResults
     * @tc.desc getScanResults invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01383_wifiManager_getScanResults', 0, async () => {
      await executeApiTestCaseById('WM_PC_01383');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01384
     * @tc.name WM_PC_01384_wifiManager_getScanResults
     * @tc.desc getScanResults invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01384_wifiManager_getScanResults', 0, async () => {
      await executeApiTestCaseById('WM_PC_01384');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01385
     * @tc.name WM_PC_01385_wifiManager_getScanResults
     * @tc.desc getScanResults invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01385_wifiManager_getScanResults', 0, async () => {
      await executeApiTestCaseById('WM_PC_01385');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01386
     * @tc.name WM_PC_01386_wifiManager_getScanResults
     * @tc.desc getScanResults invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01386_wifiManager_getScanResults', 0, async () => {
      await executeApiTestCaseById('WM_PC_01386');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01387
     * @tc.name WM_PC_01387_wifiManager_getScanResults
     * @tc.desc getScanResults invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01387_wifiManager_getScanResults', 0, async () => {
      await executeApiTestCaseById('WM_PC_01387');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01388
     * @tc.name WM_PC_01388_wifiManager_getLinkedInfo
     * @tc.desc getLinkedInfo invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01388_wifiManager_getLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01388');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01389
     * @tc.name WM_PC_01389_wifiManager_getLinkedInfo
     * @tc.desc getLinkedInfo invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01389_wifiManager_getLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01389');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01390
     * @tc.name WM_PC_01390_wifiManager_getLinkedInfo
     * @tc.desc getLinkedInfo invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01390_wifiManager_getLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01390');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01391
     * @tc.name WM_PC_01391_wifiManager_getLinkedInfo
     * @tc.desc getLinkedInfo invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01391_wifiManager_getLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01391');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01392
     * @tc.name WM_PC_01392_wifiManager_getLinkedInfo
     * @tc.desc getLinkedInfo invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01392_wifiManager_getLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01392');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01393
     * @tc.name WM_PC_01393_wifiManager_getLinkedInfo
     * @tc.desc getLinkedInfo invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01393_wifiManager_getLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01393');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01394
     * @tc.name WM_PC_01394_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01394_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01394');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01395
     * @tc.name WM_PC_01395_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01395_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01395');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01396
     * @tc.name WM_PC_01396_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01396_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01396');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01397
     * @tc.name WM_PC_01397_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01397_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01397');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01398
     * @tc.name WM_PC_01398_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01398_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01398');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01399
     * @tc.name WM_PC_01399_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01399_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01399');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01400
     * @tc.name WM_PC_01400_wifiManager_addCandidateConfig
     * @tc.desc addCandidateConfig invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01400_wifiManager_addCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01400');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01401
     * @tc.name WM_PC_01401_wifiManager_addCandidateConfig
     * @tc.desc addCandidateConfig invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01401_wifiManager_addCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01401');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01402
     * @tc.name WM_PC_01402_wifiManager_addCandidateConfig
     * @tc.desc addCandidateConfig invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01402_wifiManager_addCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01402');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01403
     * @tc.name WM_PC_01403_wifiManager_addCandidateConfig
     * @tc.desc addCandidateConfig invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01403_wifiManager_addCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01403');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01404
     * @tc.name WM_PC_01404_wifiManager_addCandidateConfig
     * @tc.desc addCandidateConfig invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01404_wifiManager_addCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01404');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01405
     * @tc.name WM_PC_01405_wifiManager_addCandidateConfig
     * @tc.desc addCandidateConfig invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01405_wifiManager_addCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01405');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01406
     * @tc.name WM_PC_01406_wifiManager_removeCandidateConfig
     * @tc.desc removeCandidateConfig invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01406_wifiManager_removeCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01406');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01407
     * @tc.name WM_PC_01407_wifiManager_removeCandidateConfig
     * @tc.desc removeCandidateConfig invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01407_wifiManager_removeCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01407');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01408
     * @tc.name WM_PC_01408_wifiManager_removeCandidateConfig
     * @tc.desc removeCandidateConfig invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01408_wifiManager_removeCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01408');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01409
     * @tc.name WM_PC_01409_wifiManager_removeCandidateConfig
     * @tc.desc removeCandidateConfig invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01409_wifiManager_removeCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01409');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01410
     * @tc.name WM_PC_01410_wifiManager_removeCandidateConfig
     * @tc.desc removeCandidateConfig invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01410_wifiManager_removeCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01410');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01411
     * @tc.name WM_PC_01411_wifiManager_removeCandidateConfig
     * @tc.desc removeCandidateConfig invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01411_wifiManager_removeCandidateConfig', 0, async () => {
      await executeApiTestCaseById('WM_PC_01411');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01412
     * @tc.name WM_PC_01412_wifiManager_getP2pLinkedInfo
     * @tc.desc getP2pLinkedInfo invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01412_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01412');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01413
     * @tc.name WM_PC_01413_wifiManager_getP2pLinkedInfo
     * @tc.desc getP2pLinkedInfo invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01413_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01413');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01414
     * @tc.name WM_PC_01414_wifiManager_getP2pLinkedInfo
     * @tc.desc getP2pLinkedInfo invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01414_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01414');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01415
     * @tc.name WM_PC_01415_wifiManager_getP2pLinkedInfo
     * @tc.desc getP2pLinkedInfo invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01415_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01415');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01416
     * @tc.name WM_PC_01416_wifiManager_getP2pLinkedInfo
     * @tc.desc getP2pLinkedInfo invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01416_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01416');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01417
     * @tc.name WM_PC_01417_wifiManager_getP2pLinkedInfo
     * @tc.desc getP2pLinkedInfo invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01417_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_PC_01417');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01418
     * @tc.name WM_PC_01418_wifiManager_getCurrentGroup
     * @tc.desc getCurrentGroup invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01418_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_PC_01418');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01419
     * @tc.name WM_PC_01419_wifiManager_getCurrentGroup
     * @tc.desc getCurrentGroup invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01419_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_PC_01419');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01420
     * @tc.name WM_PC_01420_wifiManager_getCurrentGroup
     * @tc.desc getCurrentGroup invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01420_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_PC_01420');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01421
     * @tc.name WM_PC_01421_wifiManager_getCurrentGroup
     * @tc.desc getCurrentGroup invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01421_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_PC_01421');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01422
     * @tc.name WM_PC_01422_wifiManager_getCurrentGroup
     * @tc.desc getCurrentGroup invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01422_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_PC_01422');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01423
     * @tc.name WM_PC_01423_wifiManager_getCurrentGroup
     * @tc.desc getCurrentGroup invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01423_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_PC_01423');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01424
     * @tc.name WM_PC_01424_wifiManager_getP2pPeerDevices
     * @tc.desc getP2pPeerDevices invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01424_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_PC_01424');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01425
     * @tc.name WM_PC_01425_wifiManager_getP2pPeerDevices
     * @tc.desc getP2pPeerDevices invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01425_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_PC_01425');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01426
     * @tc.name WM_PC_01426_wifiManager_getP2pPeerDevices
     * @tc.desc getP2pPeerDevices invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01426_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_PC_01426');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01427
     * @tc.name WM_PC_01427_wifiManager_getP2pPeerDevices
     * @tc.desc getP2pPeerDevices invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01427_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_PC_01427');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01428
     * @tc.name WM_PC_01428_wifiManager_getP2pPeerDevices
     * @tc.desc getP2pPeerDevices invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01428_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_PC_01428');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01429
     * @tc.name WM_PC_01429_wifiManager_getP2pPeerDevices
     * @tc.desc getP2pPeerDevices invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01429_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_PC_01429');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01430
     * @tc.name WM_PC_01430_wifiManager_getP2pLocalDevice
     * @tc.desc getP2pLocalDevice invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01430_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_PC_01430');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01431
     * @tc.name WM_PC_01431_wifiManager_getP2pLocalDevice
     * @tc.desc getP2pLocalDevice invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01431_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_PC_01431');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01432
     * @tc.name WM_PC_01432_wifiManager_getP2pLocalDevice
     * @tc.desc getP2pLocalDevice invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01432_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_PC_01432');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01433
     * @tc.name WM_PC_01433_wifiManager_getP2pLocalDevice
     * @tc.desc getP2pLocalDevice invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01433_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_PC_01433');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01434
     * @tc.name WM_PC_01434_wifiManager_getP2pLocalDevice
     * @tc.desc getP2pLocalDevice invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01434_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_PC_01434');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01435
     * @tc.name WM_PC_01435_wifiManager_getP2pLocalDevice
     * @tc.desc getP2pLocalDevice invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01435_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_PC_01435');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01436
     * @tc.name WM_PC_01436_wifiManager_getP2pGroups
     * @tc.desc getP2pGroups invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01436_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_PC_01436');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01437
     * @tc.name WM_PC_01437_wifiManager_getP2pGroups
     * @tc.desc getP2pGroups invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01437_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_PC_01437');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01438
     * @tc.name WM_PC_01438_wifiManager_getP2pGroups
     * @tc.desc getP2pGroups invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01438_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_PC_01438');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01439
     * @tc.name WM_PC_01439_wifiManager_getP2pGroups
     * @tc.desc getP2pGroups invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01439_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_PC_01439');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01440
     * @tc.name WM_PC_01440_wifiManager_getP2pGroups
     * @tc.desc getP2pGroups invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01440_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_PC_01440');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01441
     * @tc.name WM_PC_01441_wifiManager_getP2pGroups
     * @tc.desc getP2pGroups invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01441_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_PC_01441');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01442
     * @tc.name WM_PC_01442_wifiManager_connectToCandidateConfigWithUserAction
     * @tc.desc connectToCandidateConfigWithUserAction invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01442_wifiManager_connectToCandidateConfigWithUserAction', 0, async () => {
      await executeApiTestCaseById('WM_PC_01442');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01443
     * @tc.name WM_PC_01443_wifiManager_connectToCandidateConfigWithUserAction
     * @tc.desc connectToCandidateConfigWithUserAction invokeMode=promise
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01443_wifiManager_connectToCandidateConfigWithUserAction', 0, async () => {
      await executeApiTestCaseById('WM_PC_01443');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01444
     * @tc.name WM_PC_01444_wifiManager_connectToCandidateConfigWithUserAction
     * @tc.desc connectToCandidateConfigWithUserAction invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01444_wifiManager_connectToCandidateConfigWithUserAction', 0, async () => {
      await executeApiTestCaseById('WM_PC_01444');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01445
     * @tc.name WM_PC_01445_wifiManager_connectToCandidateConfigWithUserAction
     * @tc.desc connectToCandidateConfigWithUserAction invokeMode=callback
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01445_wifiManager_connectToCandidateConfigWithUserAction', 0, async () => {
      await executeApiTestCaseById('WM_PC_01445');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01446
     * @tc.name WM_PC_01446_wifiManager_connectToCandidateConfigWithUserAction
     * @tc.desc connectToCandidateConfigWithUserAction invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01446_wifiManager_connectToCandidateConfigWithUserAction', 0, async () => {
      await executeApiTestCaseById('WM_PC_01446');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_PC_01447
     * @tc.name WM_PC_01447_wifiManager_connectToCandidateConfigWithUserAction
     * @tc.desc connectToCandidateConfigWithUserAction invokeMode=sync
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_PC_01447_wifiManager_connectToCandidateConfigWithUserAction', 0, async () => {
      await executeApiTestCaseById('WM_PC_01447');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01448
     * @tc.name WM_X_01448_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=0 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01448_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01448');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01449
     * @tc.name WM_X_01449_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=0 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01449_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01449');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01450
     * @tc.name WM_X_01450_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=0 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01450_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01450');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01451
     * @tc.name WM_X_01451_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=1 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01451_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01451');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01452
     * @tc.name WM_X_01452_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=1 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01452_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01452');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01453
     * @tc.name WM_X_01453_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=1 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01453_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01453');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01454
     * @tc.name WM_X_01454_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=2 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01454_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01454');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01455
     * @tc.name WM_X_01455_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=2 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01455_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01455');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01456
     * @tc.name WM_X_01456_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=2 ip=2
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01456_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01456');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01457
     * @tc.name WM_X_01457_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=3 ip=0
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01457_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01457');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01458
     * @tc.name WM_X_01458_wifiManager_updateNetwork
     * @tc.desc updateNetwork sec=3 ip=1
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_X_01458_wifiManager_updateNetwork', 0, async () => {
      await executeApiTestCaseById('WM_X_01458');
    });

}
