/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Parameter_Coverage 分片 part04（须在 describe 内调用） */
export function register_param_part04(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01139
     * @tc.name WM_DC_01139_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=7 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01139_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01139');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01140
     * @tc.name WM_DC_01140_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=7 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01140_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01140');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01141
     * @tc.name WM_DC_01141_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=7 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01141_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01141');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01142
     * @tc.name WM_DC_01142_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=7 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01142_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01142');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01143
     * @tc.name WM_DC_01143_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=7 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01143_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01143');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01144
     * @tc.name WM_DC_01144_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=8 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01144_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01144');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01145
     * @tc.name WM_DC_01145_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=8 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01145_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01145');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01146
     * @tc.name WM_DC_01146_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=8 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01146_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01146');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01147
     * @tc.name WM_DC_01147_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=8 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01147_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01147');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01148
     * @tc.name WM_DC_01148_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=8 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01148_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01148');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01149
     * @tc.name WM_DC_01149_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=8 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01149_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01149');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01150
     * @tc.name WM_DC_01150_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=9 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01150_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01150');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01151
     * @tc.name WM_DC_01151_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=9 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01151_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01151');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01152
     * @tc.name WM_DC_01152_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=9 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01152_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01152');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01153
     * @tc.name WM_DC_01153_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=9 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01153_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01153');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01154
     * @tc.name WM_DC_01154_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=9 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01154_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01154');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01155
     * @tc.name WM_DC_01155_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=2 sec=9 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01155_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01155');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01156
     * @tc.name WM_DC_01156_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=0 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01156_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01156');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01157
     * @tc.name WM_DC_01157_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=0 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01157_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01157');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01158
     * @tc.name WM_DC_01158_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=0 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01158_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01158');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01159
     * @tc.name WM_DC_01159_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=0 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01159_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01159');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01160
     * @tc.name WM_DC_01160_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=0 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01160_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01160');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01161
     * @tc.name WM_DC_01161_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=0 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01161_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01161');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01162
     * @tc.name WM_DC_01162_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=1 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01162_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01162');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01163
     * @tc.name WM_DC_01163_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=1 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01163_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01163');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01164
     * @tc.name WM_DC_01164_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=1 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01164_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01164');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01165
     * @tc.name WM_DC_01165_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=1 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01165_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01165');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01166
     * @tc.name WM_DC_01166_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=1 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01166_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01166');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01167
     * @tc.name WM_DC_01167_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=1 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01167_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01167');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01168
     * @tc.name WM_DC_01168_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=2 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01168_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01168');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01169
     * @tc.name WM_DC_01169_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=2 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01169_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01169');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01170
     * @tc.name WM_DC_01170_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=2 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01170_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01170');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01171
     * @tc.name WM_DC_01171_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=2 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01171_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01171');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01172
     * @tc.name WM_DC_01172_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=2 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01172_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01172');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01173
     * @tc.name WM_DC_01173_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=2 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01173_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01173');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01174
     * @tc.name WM_DC_01174_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=3 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01174_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01174');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01175
     * @tc.name WM_DC_01175_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=3 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01175_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01175');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01176
     * @tc.name WM_DC_01176_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=3 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01176_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01176');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01177
     * @tc.name WM_DC_01177_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=3 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01177_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01177');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01178
     * @tc.name WM_DC_01178_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=3 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01178_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01178');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01179
     * @tc.name WM_DC_01179_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=3 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01179_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01179');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01180
     * @tc.name WM_DC_01180_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=4 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01180_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01180');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01181
     * @tc.name WM_DC_01181_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=4 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01181_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01181');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01182
     * @tc.name WM_DC_01182_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=4 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01182_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01182');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01183
     * @tc.name WM_DC_01183_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=4 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01183_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01183');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01184
     * @tc.name WM_DC_01184_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=4 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01184_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01184');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01185
     * @tc.name WM_DC_01185_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=4 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01185_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01185');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01186
     * @tc.name WM_DC_01186_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=5 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01186_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01186');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01187
     * @tc.name WM_DC_01187_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=5 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01187_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01187');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01188
     * @tc.name WM_DC_01188_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=5 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01188_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01188');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01189
     * @tc.name WM_DC_01189_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=5 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01189_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01189');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01190
     * @tc.name WM_DC_01190_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=5 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01190_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01190');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01191
     * @tc.name WM_DC_01191_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=5 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01191_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01191');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01192
     * @tc.name WM_DC_01192_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=6 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01192_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01192');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01193
     * @tc.name WM_DC_01193_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=6 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01193_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01193');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01194
     * @tc.name WM_DC_01194_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=6 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01194_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01194');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01195
     * @tc.name WM_DC_01195_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=6 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01195_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01195');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01196
     * @tc.name WM_DC_01196_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=6 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01196_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01196');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01197
     * @tc.name WM_DC_01197_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=6 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01197_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01197');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01198
     * @tc.name WM_DC_01198_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=7 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01198_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01198');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01199
     * @tc.name WM_DC_01199_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=7 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01199_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01199');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01200
     * @tc.name WM_DC_01200_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=7 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01200_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01200');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01201
     * @tc.name WM_DC_01201_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=7 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01201_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01201');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01202
     * @tc.name WM_DC_01202_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=7 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01202_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01202');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01203
     * @tc.name WM_DC_01203_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=7 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01203_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01203');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01204
     * @tc.name WM_DC_01204_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=8 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01204_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01204');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01205
     * @tc.name WM_DC_01205_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=8 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01205_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01205');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01206
     * @tc.name WM_DC_01206_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=8 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01206_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01206');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01207
     * @tc.name WM_DC_01207_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=8 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01207_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01207');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01208
     * @tc.name WM_DC_01208_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=8 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01208_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01208');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01209
     * @tc.name WM_DC_01209_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=8 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01209_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01209');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01210
     * @tc.name WM_DC_01210_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=9 ip=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01210_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01210');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01211
     * @tc.name WM_DC_01211_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=9 ip=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01211_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01211');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01212
     * @tc.name WM_DC_01212_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=9 ip=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01212_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01212');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01213
     * @tc.name WM_DC_01213_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=9 ip=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01213_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01213');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01214
     * @tc.name WM_DC_01214_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=9 ip=2 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01214_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01214');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_DC_01215
     * @tc.name WM_DC_01215_wifiManager_addDeviceConfig
     * @tc.desc addDeviceConfig ssid=3 sec=9 ip=2 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_DC_01215_wifiManager_addDeviceConfig', 0, async () => {
      await executeApiTestCaseById('WM_DC_01215');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01216
     * @tc.name WM_HC_01216_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01216_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01216');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01217
     * @tc.name WM_HC_01217_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01217_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01217');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01218
     * @tc.name WM_HC_01218_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01218_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01218');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01219
     * @tc.name WM_HC_01219_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01219_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01219');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01220
     * @tc.name WM_HC_01220_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=6 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01220_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01220');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01221
     * @tc.name WM_HC_01221_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=6 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01221_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01221');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01222
     * @tc.name WM_HC_01222_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=11 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01222_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01222');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01223
     * @tc.name WM_HC_01223_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=11 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01223_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01223');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01224
     * @tc.name WM_HC_01224_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=36 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01224_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01224');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01225
     * @tc.name WM_HC_01225_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=0 ch=36 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01225_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01225');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01226
     * @tc.name WM_HC_01226_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01226_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01226');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01227
     * @tc.name WM_HC_01227_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01227_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01227');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01228
     * @tc.name WM_HC_01228_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01228_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01228');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01229
     * @tc.name WM_HC_01229_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=1 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01229_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01229');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01230
     * @tc.name WM_HC_01230_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=6 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01230_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01230');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01231
     * @tc.name WM_HC_01231_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=6 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01231_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01231');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01232
     * @tc.name WM_HC_01232_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=11 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01232_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01232');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01233
     * @tc.name WM_HC_01233_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=11 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01233_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01233');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01234
     * @tc.name WM_HC_01234_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=36 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01234_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01234');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01235
     * @tc.name WM_HC_01235_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=1 ch=36 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01235_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01235');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01236
     * @tc.name WM_HC_01236_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=0 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01236_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01236');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01237
     * @tc.name WM_HC_01237_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=0 hidden=False
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01237_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01237');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_HC_01238
     * @tc.name WM_HC_01238_wifiManager_setHotspotConfig
     * @tc.desc setHotspotConfig band=2 ch=1 hidden=True
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WM_HC_01238_wifiManager_setHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_HC_01238');
    });

}
