/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Condition_Coverage 分片 part05（须在 describe 内调用） */
export function register_condition_part05(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00736
     * @tc.name WM_C_00736_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00736_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00736');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00737
     * @tc.name WM_C_00737_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00737_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00737');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00738
     * @tc.name WM_C_00738_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00738_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00738');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00739
     * @tc.name WM_C_00739_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00739_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00739');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00740
     * @tc.name WM_C_00740_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00740_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00740');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00741
     * @tc.name WM_C_00741_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00741_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00741');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00742
     * @tc.name WM_C_00742_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00742_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00742');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00743
     * @tc.name WM_C_00743_wifiManager_getP2pLocalDevice
     * @tc.desc wifiManager.getP2pLocalDevice condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00743_wifiManager_getP2pLocalDevice', 0, async () => {
      await executeApiTestCaseById('WM_C_00743');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00744
     * @tc.name WM_C_00744_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00744_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00744');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00745
     * @tc.name WM_C_00745_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00745_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00745');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00746
     * @tc.name WM_C_00746_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00746_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00746');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00747
     * @tc.name WM_C_00747_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00747_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00747');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00748
     * @tc.name WM_C_00748_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00748_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00748');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00749
     * @tc.name WM_C_00749_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00749_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00749');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00750
     * @tc.name WM_C_00750_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00750_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00750');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00751
     * @tc.name WM_C_00751_wifiManager_getP2pGroups
     * @tc.desc wifiManager.getP2pGroups condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00751_wifiManager_getP2pGroups', 0, async () => {
      await executeApiTestCaseById('WM_C_00751');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00752
     * @tc.name WM_C_00752_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00752_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00752');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00753
     * @tc.name WM_C_00753_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00753_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00753');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00754
     * @tc.name WM_C_00754_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00754_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00754');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00755
     * @tc.name WM_C_00755_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00755_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00755');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00756
     * @tc.name WM_C_00756_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00756_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00756');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00757
     * @tc.name WM_C_00757_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00757_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00757');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00758
     * @tc.name WM_C_00758_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00758_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00758');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00759
     * @tc.name WM_C_00759_wifiManager_removeGroup
     * @tc.desc wifiManager.removeGroup condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00759_wifiManager_removeGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00759');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00760
     * @tc.name WM_C_00760_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00760_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00760');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00761
     * @tc.name WM_C_00761_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00761_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00761');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00762
     * @tc.name WM_C_00762_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00762_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00762');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00763
     * @tc.name WM_C_00763_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00763_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00763');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00764
     * @tc.name WM_C_00764_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00764_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00764');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00765
     * @tc.name WM_C_00765_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00765_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00765');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00766
     * @tc.name WM_C_00766_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00766_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00766');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00767
     * @tc.name WM_C_00767_wifiManager_p2pCancelConnect
     * @tc.desc wifiManager.p2pCancelConnect condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00767_wifiManager_p2pCancelConnect', 0, async () => {
      await executeApiTestCaseById('WM_C_00767');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00768
     * @tc.name WM_C_00768_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00768_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00768');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00769
     * @tc.name WM_C_00769_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00769_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00769');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00770
     * @tc.name WM_C_00770_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00770_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00770');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00771
     * @tc.name WM_C_00771_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00771_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00771');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00772
     * @tc.name WM_C_00772_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00772_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00772');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00773
     * @tc.name WM_C_00773_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00773_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00773');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00774
     * @tc.name WM_C_00774_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00774_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00774');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00775
     * @tc.name WM_C_00775_wifiManager_stopDiscoverDevices
     * @tc.desc wifiManager.stopDiscoverDevices condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00775_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00775');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00776
     * @tc.name WM_C_00776_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00776_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00776');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00777
     * @tc.name WM_C_00777_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00777_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00777');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00778
     * @tc.name WM_C_00778_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00778_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00778');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00779
     * @tc.name WM_C_00779_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00779_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00779');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00780
     * @tc.name WM_C_00780_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00780_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00780');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00781
     * @tc.name WM_C_00781_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00781_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00781');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00782
     * @tc.name WM_C_00782_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00782_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00782');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00783
     * @tc.name WM_C_00783_wifiManager_deletePersistentGroup
     * @tc.desc wifiManager.deletePersistentGroup condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00783_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00783');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00784
     * @tc.name WM_C_00784_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00784_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00784');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00785
     * @tc.name WM_C_00785_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00785_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00785');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00786
     * @tc.name WM_C_00786_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00786_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00786');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00787
     * @tc.name WM_C_00787_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00787_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00787');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00788
     * @tc.name WM_C_00788_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00788_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00788');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00789
     * @tc.name WM_C_00789_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00789_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00789');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00790
     * @tc.name WM_C_00790_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00790_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00790');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00791
     * @tc.name WM_C_00791_wifiManager_setDeviceName
     * @tc.desc wifiManager.setDeviceName condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00791_wifiManager_setDeviceName', 0, async () => {
      await executeApiTestCaseById('WM_C_00791');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00792
     * @tc.name WM_C_00792_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00792_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00792');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00793
     * @tc.name WM_C_00793_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00793_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00793');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00794
     * @tc.name WM_C_00794_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00794_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00794');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00795
     * @tc.name WM_C_00795_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00795_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00795');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00796
     * @tc.name WM_C_00796_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00796_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00796');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00797
     * @tc.name WM_C_00797_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00797_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00797');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00798
     * @tc.name WM_C_00798_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00798_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00798');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00799
     * @tc.name WM_C_00799_wifiManager_startDiscoverDevices
     * @tc.desc wifiManager.startDiscoverDevices condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00799_wifiManager_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00799');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01262
     * @tc.name WM_E_01262_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange register under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01262_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01262');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01263
     * @tc.name WM_E_01263_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange register under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01263_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01263');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01264
     * @tc.name WM_E_01264_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange register under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01264_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01264');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01265
     * @tc.name WM_E_01265_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange register under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01265_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01265');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01266
     * @tc.name WM_E_01266_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange unregister under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01266_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01266');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01267
     * @tc.name WM_E_01267_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange unregister under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01267_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01267');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01268
     * @tc.name WM_E_01268_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange unregister under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01268_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01268');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01269
     * @tc.name WM_E_01269_wifiManager_on_wifiStateChange
     * @tc.desc event wifiStateChange unregister under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01269_wifiManager_on_wifiStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01269');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01270
     * @tc.name WM_E_01270_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange register under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01270_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01270');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01271
     * @tc.name WM_E_01271_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange register under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01271_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01271');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01272
     * @tc.name WM_E_01272_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange register under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01272_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01272');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01273
     * @tc.name WM_E_01273_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange register under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01273_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01273');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01274
     * @tc.name WM_E_01274_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange unregister under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01274_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01274');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01275
     * @tc.name WM_E_01275_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange unregister under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01275_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01275');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01276
     * @tc.name WM_E_01276_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange unregister under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01276_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01276');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01277
     * @tc.name WM_E_01277_wifiManager_on_wifiConnectionChange
     * @tc.desc event wifiConnectionChange unregister under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01277_wifiManager_on_wifiConnectionChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01277');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01278
     * @tc.name WM_E_01278_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange register under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01278_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01278');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01279
     * @tc.name WM_E_01279_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange register under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01279_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01279');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01280
     * @tc.name WM_E_01280_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange register under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01280_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01280');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01281
     * @tc.name WM_E_01281_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange register under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01281_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01281');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01282
     * @tc.name WM_E_01282_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange unregister under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01282_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01282');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01283
     * @tc.name WM_E_01283_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange unregister under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01283_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01283');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01284
     * @tc.name WM_E_01284_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange unregister under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01284_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01284');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01285
     * @tc.name WM_E_01285_wifiManager_on_wifiScanStateChange
     * @tc.desc event wifiScanStateChange unregister under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01285_wifiManager_on_wifiScanStateChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01285');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01286
     * @tc.name WM_E_01286_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange register under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01286_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01286');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01287
     * @tc.name WM_E_01287_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange register under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01287_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01287');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01288
     * @tc.name WM_E_01288_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange register under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01288_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01288');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01289
     * @tc.name WM_E_01289_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange register under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01289_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01289');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01290
     * @tc.name WM_E_01290_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange unregister under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01290_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01290');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01291
     * @tc.name WM_E_01291_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange unregister under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01291_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01291');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01292
     * @tc.name WM_E_01292_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange unregister under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01292_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01292');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01293
     * @tc.name WM_E_01293_wifiManager_on_wifiRssiChange
     * @tc.desc event wifiRssiChange unregister under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01293_wifiManager_on_wifiRssiChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01293');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01294
     * @tc.name WM_E_01294_wifiManager_on_streamChange
     * @tc.desc event streamChange register under WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01294_wifiManager_on_streamChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01294');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01295
     * @tc.name WM_E_01295_wifiManager_on_streamChange
     * @tc.desc event streamChange register under HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01295_wifiManager_on_streamChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01295');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01296
     * @tc.name WM_E_01296_wifiManager_on_streamChange
     * @tc.desc event streamChange register under P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01296_wifiManager_on_streamChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01296');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_E_01297
     * @tc.name WM_E_01297_wifiManager_on_streamChange
     * @tc.desc event streamChange register under P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_E_01297_wifiManager_on_streamChange', 0, async () => {
      await executeApiTestCaseById('WM_E_01297');
    });

}
