/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Combination_Coverage 分片 part01（须在 describe 内调用） */
export function register_combo_part01(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00800
     * @tc.name WM_CB_00800_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#0 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00800_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00800');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00801
     * @tc.name WM_CB_00801_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#1 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00801_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00801');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00802
     * @tc.name WM_CB_00802_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#2 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00802_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00802');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00803
     * @tc.name WM_CB_00803_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#3 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00803_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00803');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00804
     * @tc.name WM_CB_00804_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#4 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00804_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00804');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00805
     * @tc.name WM_CB_00805_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#5 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00805_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00805');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00806
     * @tc.name WM_CB_00806_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#6 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00806_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00806');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00807
     * @tc.name WM_CB_00807_wifiManager_getScanInfoList
     * @tc.desc combo flow#0 var#7 -> getScanInfoList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00807_wifiManager_getScanInfoList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00807');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00808
     * @tc.name WM_CB_00808_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#0 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00808_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00808');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00809
     * @tc.name WM_CB_00809_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#1 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00809_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00809');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00810
     * @tc.name WM_CB_00810_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#2 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00810_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00810');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00811
     * @tc.name WM_CB_00811_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#3 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00811_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00811');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00812
     * @tc.name WM_CB_00812_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#4 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00812_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00812');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00813
     * @tc.name WM_CB_00813_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#5 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00813_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00813');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00814
     * @tc.name WM_CB_00814_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#6 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00814_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00814');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00815
     * @tc.name WM_CB_00815_wifiManager_getWifiDetailState
     * @tc.desc combo flow#1 var#7 -> getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00815_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_CB_00815');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00816
     * @tc.name WM_CB_00816_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#0 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00816_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00816');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00817
     * @tc.name WM_CB_00817_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#1 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00817_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00817');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00818
     * @tc.name WM_CB_00818_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#2 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00818_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00818');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00819
     * @tc.name WM_CB_00819_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#3 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00819_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00819');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00820
     * @tc.name WM_CB_00820_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#4 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00820_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00820');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00821
     * @tc.name WM_CB_00821_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#5 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00821_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00821');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00822
     * @tc.name WM_CB_00822_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#6 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00822_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00822');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00823
     * @tc.name WM_CB_00823_wifiManager_getCountryCode
     * @tc.desc combo flow#2 var#7 -> getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00823_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_CB_00823');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00824
     * @tc.name WM_CB_00824_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#0 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00824_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00824');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00825
     * @tc.name WM_CB_00825_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#1 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00825_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00825');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00826
     * @tc.name WM_CB_00826_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#2 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00826_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00826');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00827
     * @tc.name WM_CB_00827_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#3 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00827_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00827');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00828
     * @tc.name WM_CB_00828_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#4 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00828_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00828');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00829
     * @tc.name WM_CB_00829_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#5 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00829_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00829');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00830
     * @tc.name WM_CB_00830_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#6 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00830_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00830');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00831
     * @tc.name WM_CB_00831_wifiManager_getIpv6Info
     * @tc.desc combo flow#3 var#7 -> getIpv6Info
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00831_wifiManager_getIpv6Info', 0, async () => {
      await executeApiTestCaseById('WM_CB_00831');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00832
     * @tc.name WM_CB_00832_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#0 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00832_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00832');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00833
     * @tc.name WM_CB_00833_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#1 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00833_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00833');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00834
     * @tc.name WM_CB_00834_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#2 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00834_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00834');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00835
     * @tc.name WM_CB_00835_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#3 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00835_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00835');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00836
     * @tc.name WM_CB_00836_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#4 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00836_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00836');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00837
     * @tc.name WM_CB_00837_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#5 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00837_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00837');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00838
     * @tc.name WM_CB_00838_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#6 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00838_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00838');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00839
     * @tc.name WM_CB_00839_wifiManager_getDisconnectedReason
     * @tc.desc combo flow#4 var#7 -> getDisconnectedReason
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00839_wifiManager_getDisconnectedReason', 0, async () => {
      await executeApiTestCaseById('WM_CB_00839');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00840
     * @tc.name WM_CB_00840_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#0 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00840_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00840');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00841
     * @tc.name WM_CB_00841_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#1 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00841_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00841');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00842
     * @tc.name WM_CB_00842_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#2 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00842_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00842');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00843
     * @tc.name WM_CB_00843_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#3 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00843_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00843');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00844
     * @tc.name WM_CB_00844_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#4 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00844_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00844');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00845
     * @tc.name WM_CB_00845_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#5 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00845_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00845');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00846
     * @tc.name WM_CB_00846_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#6 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00846_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00846');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00847
     * @tc.name WM_CB_00847_wifiManager_getScanAlwaysAllowed
     * @tc.desc combo flow#5 var#7 -> getScanAlwaysAllowed
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00847_wifiManager_getScanAlwaysAllowed', 0, async () => {
      await executeApiTestCaseById('WM_CB_00847');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00848
     * @tc.name WM_CB_00848_wifiManager_startScan
     * @tc.desc combo flow#6 var#0 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00848_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00848');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00849
     * @tc.name WM_CB_00849_wifiManager_startScan
     * @tc.desc combo flow#6 var#1 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00849_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00849');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00850
     * @tc.name WM_CB_00850_wifiManager_startScan
     * @tc.desc combo flow#6 var#2 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00850_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00850');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00851
     * @tc.name WM_CB_00851_wifiManager_startScan
     * @tc.desc combo flow#6 var#3 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00851_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00851');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00852
     * @tc.name WM_CB_00852_wifiManager_startScan
     * @tc.desc combo flow#6 var#4 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00852_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00852');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00853
     * @tc.name WM_CB_00853_wifiManager_startScan
     * @tc.desc combo flow#6 var#5 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00853_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00853');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00854
     * @tc.name WM_CB_00854_wifiManager_startScan
     * @tc.desc combo flow#6 var#6 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00854_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00854');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00855
     * @tc.name WM_CB_00855_wifiManager_startScan
     * @tc.desc combo flow#6 var#7 -> startScan
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00855_wifiManager_startScan', 0, async () => {
      await executeApiTestCaseById('WM_CB_00855');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00856
     * @tc.name WM_CB_00856_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#0 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00856_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00856');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00857
     * @tc.name WM_CB_00857_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#1 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00857_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00857');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00858
     * @tc.name WM_CB_00858_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#2 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00858_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00858');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00859
     * @tc.name WM_CB_00859_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#3 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00859_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00859');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00860
     * @tc.name WM_CB_00860_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#4 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00860_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00860');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00861
     * @tc.name WM_CB_00861_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#5 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00861_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00861');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00862
     * @tc.name WM_CB_00862_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#6 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00862_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00862');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00863
     * @tc.name WM_CB_00863_wifiManager_getSignalLevel
     * @tc.desc combo flow#7 var#7 -> getSignalLevel
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00863_wifiManager_getSignalLevel', 0, async () => {
      await executeApiTestCaseById('WM_CB_00863');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00864
     * @tc.name WM_CB_00864_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#0 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00864_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00864');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00865
     * @tc.name WM_CB_00865_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#1 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00865_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00865');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00866
     * @tc.name WM_CB_00866_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#2 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00866_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00866');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00867
     * @tc.name WM_CB_00867_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#3 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00867_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00867');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00868
     * @tc.name WM_CB_00868_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#4 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00868_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00868');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00869
     * @tc.name WM_CB_00869_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#5 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00869_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00869');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00870
     * @tc.name WM_CB_00870_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#6 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00870_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00870');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00871
     * @tc.name WM_CB_00871_wifiManager_isBandTypeSupported
     * @tc.desc combo flow#8 var#7 -> isBandTypeSupported
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00871_wifiManager_isBandTypeSupported', 0, async () => {
      await executeApiTestCaseById('WM_CB_00871');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00872
     * @tc.name WM_CB_00872_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#0 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00872_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00872');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00873
     * @tc.name WM_CB_00873_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#1 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00873_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00873');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00874
     * @tc.name WM_CB_00874_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#2 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00874_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00874');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00875
     * @tc.name WM_CB_00875_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#3 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00875_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00875');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00876
     * @tc.name WM_CB_00876_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#4 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00876_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00876');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00877
     * @tc.name WM_CB_00877_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#5 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00877_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00877');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00878
     * @tc.name WM_CB_00878_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#6 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00878_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00878');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00879
     * @tc.name WM_CB_00879_wifiManager_isWifiActive
     * @tc.desc combo flow#9 var#7 -> isWifiActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00879_wifiManager_isWifiActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00879');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00880
     * @tc.name WM_CB_00880_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#0 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00880_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00880');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00881
     * @tc.name WM_CB_00881_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#1 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00881_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00881');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00882
     * @tc.name WM_CB_00882_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#2 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00882_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00882');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00883
     * @tc.name WM_CB_00883_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#3 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00883_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00883');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00884
     * @tc.name WM_CB_00884_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#4 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00884_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00884');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00885
     * @tc.name WM_CB_00885_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#5 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00885_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00885');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00886
     * @tc.name WM_CB_00886_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#6 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00886_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00886');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00887
     * @tc.name WM_CB_00887_wifiManager_getHotspotConfig
     * @tc.desc combo flow#10 var#7 -> getHotspotConfig
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00887_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_CB_00887');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00888
     * @tc.name WM_CB_00888_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#0 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00888_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00888');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00889
     * @tc.name WM_CB_00889_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#1 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00889_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00889');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00890
     * @tc.name WM_CB_00890_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#2 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00890_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00890');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00891
     * @tc.name WM_CB_00891_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#3 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00891_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00891');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00892
     * @tc.name WM_CB_00892_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#4 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00892_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00892');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00893
     * @tc.name WM_CB_00893_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#5 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00893_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00893');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00894
     * @tc.name WM_CB_00894_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#6 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00894_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00894');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00895
     * @tc.name WM_CB_00895_wifiManager_disableHotspot
     * @tc.desc combo flow#11 var#7 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00895_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_CB_00895');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00896
     * @tc.name WM_CB_00896_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#0 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00896_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00896');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00897
     * @tc.name WM_CB_00897_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#1 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00897_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00897');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00898
     * @tc.name WM_CB_00898_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#2 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00898_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00898');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00899
     * @tc.name WM_CB_00899_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#3 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00899_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00899');
    });

}
