/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Condition_Coverage 分片 part04（须在 describe 内调用） */
export function register_condition_part04(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00636
     * @tc.name WM_C_00636_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00636_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00636');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00637
     * @tc.name WM_C_00637_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00637_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00637');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00638
     * @tc.name WM_C_00638_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00638_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00638');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00639
     * @tc.name WM_C_00639_wifiManager_isMeteredHotspot
     * @tc.desc wifiManager.isMeteredHotspot condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00639_wifiManager_isMeteredHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00639');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00640
     * @tc.name WM_C_00640_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00640_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00640');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00641
     * @tc.name WM_C_00641_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00641_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00641');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00642
     * @tc.name WM_C_00642_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00642_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00642');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00643
     * @tc.name WM_C_00643_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00643_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00643');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00644
     * @tc.name WM_C_00644_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00644_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00644');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00645
     * @tc.name WM_C_00645_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00645_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00645');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00646
     * @tc.name WM_C_00646_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00646_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00646');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00647
     * @tc.name WM_C_00647_wifiManager_factoryReset
     * @tc.desc wifiManager.factoryReset condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00647_wifiManager_factoryReset', 0, async () => {
      await executeApiTestCaseById('WM_C_00647');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00648
     * @tc.name WM_C_00648_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00648_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00648');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00649
     * @tc.name WM_C_00649_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00649_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00649');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00650
     * @tc.name WM_C_00650_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00650_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00650');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00651
     * @tc.name WM_C_00651_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00651_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00651');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00652
     * @tc.name WM_C_00652_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00652_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00652');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00653
     * @tc.name WM_C_00653_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00653_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00653');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00654
     * @tc.name WM_C_00654_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00654_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00654');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00655
     * @tc.name WM_C_00655_wifiManager_isOpenSoftApAllowed
     * @tc.desc wifiManager.isOpenSoftApAllowed condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00655_wifiManager_isOpenSoftApAllowed', 0, async () => {
      await executeApiTestCaseById('WM_C_00655');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00656
     * @tc.name WM_C_00656_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00656_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00656');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00657
     * @tc.name WM_C_00657_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00657_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00657');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00658
     * @tc.name WM_C_00658_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00658_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00658');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00659
     * @tc.name WM_C_00659_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00659_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00659');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00660
     * @tc.name WM_C_00660_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00660_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00660');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00661
     * @tc.name WM_C_00661_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00661_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00661');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00662
     * @tc.name WM_C_00662_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00662_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00662');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00663
     * @tc.name WM_C_00663_wifiManager_enableHotspot
     * @tc.desc wifiManager.enableHotspot condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00663_wifiManager_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00663');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00664
     * @tc.name WM_C_00664_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00664_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00664');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00665
     * @tc.name WM_C_00665_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00665_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00665');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00666
     * @tc.name WM_C_00666_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00666_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00666');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00667
     * @tc.name WM_C_00667_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00667_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00667');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00668
     * @tc.name WM_C_00668_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00668_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00668');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00669
     * @tc.name WM_C_00669_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00669_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00669');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00670
     * @tc.name WM_C_00670_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00670_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00670');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00671
     * @tc.name WM_C_00671_wifiManager_disableHotspot
     * @tc.desc wifiManager.disableHotspot condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00671_wifiManager_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WM_C_00671');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00672
     * @tc.name WM_C_00672_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00672_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00672');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00673
     * @tc.name WM_C_00673_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00673_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00673');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00674
     * @tc.name WM_C_00674_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00674_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00674');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00675
     * @tc.name WM_C_00675_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00675_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00675');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00676
     * @tc.name WM_C_00676_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00676_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00676');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00677
     * @tc.name WM_C_00677_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00677_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00677');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00678
     * @tc.name WM_C_00678_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00678_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00678');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00679
     * @tc.name WM_C_00679_wifiManager_isHotspotDualBandSupported
     * @tc.desc wifiManager.isHotspotDualBandSupported condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00679_wifiManager_isHotspotDualBandSupported', 0, async () => {
      await executeApiTestCaseById('WM_C_00679');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00680
     * @tc.name WM_C_00680_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00680_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00680');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00681
     * @tc.name WM_C_00681_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00681_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00681');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00682
     * @tc.name WM_C_00682_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00682_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00682');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00683
     * @tc.name WM_C_00683_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00683_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00683');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00684
     * @tc.name WM_C_00684_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00684_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00684');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00685
     * @tc.name WM_C_00685_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00685_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00685');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00686
     * @tc.name WM_C_00686_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00686_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00686');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00687
     * @tc.name WM_C_00687_wifiManager_isHotspotActive
     * @tc.desc wifiManager.isHotspotActive condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00687_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_C_00687');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00688
     * @tc.name WM_C_00688_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00688_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00688');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00689
     * @tc.name WM_C_00689_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00689_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00689');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00690
     * @tc.name WM_C_00690_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00690_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00690');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00691
     * @tc.name WM_C_00691_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00691_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00691');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00692
     * @tc.name WM_C_00692_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00692_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00692');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00693
     * @tc.name WM_C_00693_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00693_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00693');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00694
     * @tc.name WM_C_00694_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00694_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00694');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00695
     * @tc.name WM_C_00695_wifiManager_getHotspotConfig
     * @tc.desc wifiManager.getHotspotConfig condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00695_wifiManager_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WM_C_00695');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00696
     * @tc.name WM_C_00696_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00696_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00696');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00697
     * @tc.name WM_C_00697_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00697_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00697');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00698
     * @tc.name WM_C_00698_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00698_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00698');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00699
     * @tc.name WM_C_00699_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00699_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00699');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00700
     * @tc.name WM_C_00700_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00700_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00700');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00701
     * @tc.name WM_C_00701_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00701_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00701');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00702
     * @tc.name WM_C_00702_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00702_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00702');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00703
     * @tc.name WM_C_00703_wifiManager_getStations
     * @tc.desc wifiManager.getStations condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00703_wifiManager_getStations', 0, async () => {
      await executeApiTestCaseById('WM_C_00703');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00704
     * @tc.name WM_C_00704_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00704_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00704');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00705
     * @tc.name WM_C_00705_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00705_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00705');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00706
     * @tc.name WM_C_00706_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00706_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00706');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00707
     * @tc.name WM_C_00707_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00707_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00707');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00708
     * @tc.name WM_C_00708_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00708_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00708');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00709
     * @tc.name WM_C_00709_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00709_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00709');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00710
     * @tc.name WM_C_00710_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00710_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00710');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00711
     * @tc.name WM_C_00711_wifiManager_getHotspotBlockList
     * @tc.desc wifiManager.getHotspotBlockList condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00711_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_C_00711');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00712
     * @tc.name WM_C_00712_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00712_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00712');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00713
     * @tc.name WM_C_00713_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00713_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00713');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00714
     * @tc.name WM_C_00714_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00714_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00714');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00715
     * @tc.name WM_C_00715_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00715_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00715');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00716
     * @tc.name WM_C_00716_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00716_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00716');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00717
     * @tc.name WM_C_00717_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00717_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00717');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00718
     * @tc.name WM_C_00718_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00718_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00718');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00719
     * @tc.name WM_C_00719_wifiManager_getP2pLinkedInfo
     * @tc.desc wifiManager.getP2pLinkedInfo condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00719_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_C_00719');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00720
     * @tc.name WM_C_00720_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00720_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00720');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00721
     * @tc.name WM_C_00721_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00721_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00721');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00722
     * @tc.name WM_C_00722_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00722_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00722');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00723
     * @tc.name WM_C_00723_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00723_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00723');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00724
     * @tc.name WM_C_00724_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00724_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00724');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00725
     * @tc.name WM_C_00725_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00725_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00725');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00726
     * @tc.name WM_C_00726_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00726_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00726');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00727
     * @tc.name WM_C_00727_wifiManager_getCurrentGroup
     * @tc.desc wifiManager.getCurrentGroup condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00727_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_C_00727');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00728
     * @tc.name WM_C_00728_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00728_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00728');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00729
     * @tc.name WM_C_00729_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=WIFI_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00729_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00729');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00730
     * @tc.name WM_C_00730_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=WIFI_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00730_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00730');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00731
     * @tc.name WM_C_00731_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=WIFI_ON_SCAN
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00731_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00731');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00732
     * @tc.name WM_C_00732_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=HOTSPOT_OFF
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00732_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00732');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00733
     * @tc.name WM_C_00733_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=HOTSPOT_ON
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00733_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00733');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00734
     * @tc.name WM_C_00734_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=P2P_IDLE
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00734_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00734');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_C_00735
     * @tc.name WM_C_00735_wifiManager_getP2pPeerDevices
     * @tc.desc wifiManager.getP2pPeerDevices condition=P2P_DISCOVERING
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 2
     */
    it('WM_C_00735_wifiManager_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WM_C_00735');
    });

}
