/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Parameter_Coverage 分片 part07（须在 describe 内调用） */
export function register_param_part07(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01590
     * @tc.name WF_P_01590_wifi_isFeatureSupported
     * @tc.desc wifi.isFeatureSupported param#7 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01590_wifi_isFeatureSupported', 0, async () => {
      await executeApiTestCaseById('WF_P_01590');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01591
     * @tc.name WF_P_01591_wifi_enableHotspot
     * @tc.desc wifi.enableHotspot param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01591_wifi_enableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_P_01591');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01592
     * @tc.name WF_P_01592_wifi_disableHotspot
     * @tc.desc wifi.disableHotspot param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01592_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_P_01592');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01593
     * @tc.name WF_P_01593_wifi_isHotspotActive
     * @tc.desc wifi.isHotspotActive param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01593_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_P_01593');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01594
     * @tc.name WF_P_01594_wifi_getHotspotConfig
     * @tc.desc wifi.getHotspotConfig param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01594_wifi_getHotspotConfig', 0, async () => {
      await executeApiTestCaseById('WF_P_01594');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01595
     * @tc.name WF_P_01595_wifi_getP2pPeerDevices
     * @tc.desc wifi.getP2pPeerDevices param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01595_wifi_getP2pPeerDevices', 0, async () => {
      await executeApiTestCaseById('WF_P_01595');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01596
     * @tc.name WF_P_01596_wifi_startDiscoverDevices
     * @tc.desc wifi.startDiscoverDevices param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01596_wifi_startDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_P_01596');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_P_01597
     * @tc.name WF_P_01597_wifi_stopDiscoverDevices
     * @tc.desc wifi.stopDiscoverDevices param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('WF_P_01597_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_P_01597');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01970
     * @tc.name LE_P_01970_linkEnhance_createServer
     * @tc.desc linkEnhance.createServer param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01970_linkEnhance_createServer', 0, async () => {
      await executeApiTestCaseById('LE_P_01970');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01971
     * @tc.name LE_P_01971_linkEnhance_createServer
     * @tc.desc linkEnhance.createServer param#1 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01971_linkEnhance_createServer', 0, async () => {
      await executeApiTestCaseById('LE_P_01971');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01972
     * @tc.name LE_P_01972_linkEnhance_createServer
     * @tc.desc linkEnhance.createServer param#2 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01972_linkEnhance_createServer', 0, async () => {
      await executeApiTestCaseById('LE_P_01972');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01973
     * @tc.name LE_P_01973_linkEnhance_createConnection
     * @tc.desc linkEnhance.createConnection param#0 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01973_linkEnhance_createConnection', 0, async () => {
      await executeApiTestCaseById('LE_P_01973');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01974
     * @tc.name LE_P_01974_linkEnhance_createConnection
     * @tc.desc linkEnhance.createConnection param#1 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01974_linkEnhance_createConnection', 0, async () => {
      await executeApiTestCaseById('LE_P_01974');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01975
     * @tc.name LE_P_01975_linkEnhance_createConnection
     * @tc.desc linkEnhance.createConnection param#2 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01975_linkEnhance_createConnection', 0, async () => {
      await executeApiTestCaseById('LE_P_01975');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01976
     * @tc.name LE_P_01976_linkEnhance_createConnection
     * @tc.desc linkEnhance.createConnection param#3 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01976_linkEnhance_createConnection', 0, async () => {
      await executeApiTestCaseById('LE_P_01976');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01977
     * @tc.name LE_P_01977_linkEnhance_createConnection
     * @tc.desc linkEnhance.createConnection param#4 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01977_linkEnhance_createConnection', 0, async () => {
      await executeApiTestCaseById('LE_P_01977');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_LE_P_01978
     * @tc.name LE_P_01978_linkEnhance_createConnection
     * @tc.desc linkEnhance.createConnection param#5 precond=ANY
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('LE_P_01978_linkEnhance_createConnection', 0, async () => {
      await executeApiTestCaseById('LE_P_01978');
    });

}
