/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Combination_Coverage 分片 part04（须在 describe 内调用） */
export function register_combo_part04(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01887
     * @tc.name WF_CB_01887_wifi_disableHotspot
     * @tc.desc combo flow#11 var#5 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01887_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_CB_01887');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01888
     * @tc.name WF_CB_01888_wifi_disableHotspot
     * @tc.desc combo flow#11 var#6 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01888_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_CB_01888');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01889
     * @tc.name WF_CB_01889_wifi_disableHotspot
     * @tc.desc combo flow#11 var#7 -> disableHotspot
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01889_wifi_disableHotspot', 0, async () => {
      await executeApiTestCaseById('WF_CB_01889');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01890
     * @tc.name WF_CB_01890_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#0 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01890_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01890');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01891
     * @tc.name WF_CB_01891_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#1 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01891_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01891');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01892
     * @tc.name WF_CB_01892_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#2 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01892_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01892');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01893
     * @tc.name WF_CB_01893_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#3 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01893_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01893');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01894
     * @tc.name WF_CB_01894_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#4 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01894_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01894');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01895
     * @tc.name WF_CB_01895_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#5 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01895_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01895');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01896
     * @tc.name WF_CB_01896_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#6 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01896_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01896');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01897
     * @tc.name WF_CB_01897_wifi_getHotspotBlockList
     * @tc.desc combo flow#12 var#7 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01897_wifi_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WF_CB_01897');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01898
     * @tc.name WF_CB_01898_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#0 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01898_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01898');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01899
     * @tc.name WF_CB_01899_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#1 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01899_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01899');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01900
     * @tc.name WF_CB_01900_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#2 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01900_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01900');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01901
     * @tc.name WF_CB_01901_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#3 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01901_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01901');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01902
     * @tc.name WF_CB_01902_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#4 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01902_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01902');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01903
     * @tc.name WF_CB_01903_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#5 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01903_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01903');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01904
     * @tc.name WF_CB_01904_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#6 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01904_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01904');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01905
     * @tc.name WF_CB_01905_wifi_isHotspotActive
     * @tc.desc combo flow#13 var#7 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01905_wifi_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WF_CB_01905');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01906
     * @tc.name WF_CB_01906_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#0 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01906_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01906');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01907
     * @tc.name WF_CB_01907_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#1 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01907_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01907');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01908
     * @tc.name WF_CB_01908_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#2 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01908_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01908');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01909
     * @tc.name WF_CB_01909_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#3 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01909_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01909');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01910
     * @tc.name WF_CB_01910_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#4 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01910_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01910');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01911
     * @tc.name WF_CB_01911_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#5 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01911_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01911');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01912
     * @tc.name WF_CB_01912_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#6 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01912_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01912');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01913
     * @tc.name WF_CB_01913_wifi_stopDiscoverDevices
     * @tc.desc combo flow#14 var#7 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01913_wifi_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WF_CB_01913');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01914
     * @tc.name WF_CB_01914_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#0 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01914_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01914');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01915
     * @tc.name WF_CB_01915_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#1 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01915_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01915');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01916
     * @tc.name WF_CB_01916_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#2 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01916_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01916');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01917
     * @tc.name WF_CB_01917_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#3 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01917_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01917');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01918
     * @tc.name WF_CB_01918_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#4 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01918_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01918');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01919
     * @tc.name WF_CB_01919_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#5 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01919_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01919');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01920
     * @tc.name WF_CB_01920_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#6 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01920_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01920');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01921
     * @tc.name WF_CB_01921_wifi_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#7 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01921_wifi_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WF_CB_01921');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01922
     * @tc.name WF_CB_01922_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#0 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01922_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01922');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01923
     * @tc.name WF_CB_01923_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#1 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01923_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01923');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01924
     * @tc.name WF_CB_01924_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#2 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01924_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01924');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01925
     * @tc.name WF_CB_01925_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#3 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01925_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01925');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01926
     * @tc.name WF_CB_01926_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#4 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01926_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01926');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01927
     * @tc.name WF_CB_01927_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#5 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01927_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01927');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01928
     * @tc.name WF_CB_01928_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#6 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01928_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01928');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01929
     * @tc.name WF_CB_01929_wifi_getCurrentGroup
     * @tc.desc combo flow#16 var#7 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01929_wifi_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01929');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01930
     * @tc.name WF_CB_01930_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#0 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01930_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01930');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01931
     * @tc.name WF_CB_01931_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#1 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01931_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01931');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01932
     * @tc.name WF_CB_01932_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#2 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01932_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01932');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01933
     * @tc.name WF_CB_01933_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#3 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01933_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01933');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01934
     * @tc.name WF_CB_01934_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#4 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01934_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01934');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01935
     * @tc.name WF_CB_01935_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#5 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01935_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01935');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01936
     * @tc.name WF_CB_01936_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#6 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01936_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01936');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01937
     * @tc.name WF_CB_01937_wifi_deletePersistentGroup
     * @tc.desc combo flow#17 var#7 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01937_wifi_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WF_CB_01937');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01938
     * @tc.name WF_CB_01938_wifi_disableWifi
     * @tc.desc combo flow#18 var#0 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01938_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01938');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01939
     * @tc.name WF_CB_01939_wifi_disableWifi
     * @tc.desc combo flow#18 var#1 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01939_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01939');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01940
     * @tc.name WF_CB_01940_wifi_disableWifi
     * @tc.desc combo flow#18 var#2 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01940_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01940');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01941
     * @tc.name WF_CB_01941_wifi_disableWifi
     * @tc.desc combo flow#18 var#3 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01941_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01941');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01942
     * @tc.name WF_CB_01942_wifi_disableWifi
     * @tc.desc combo flow#18 var#4 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01942_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01942');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01943
     * @tc.name WF_CB_01943_wifi_disableWifi
     * @tc.desc combo flow#18 var#5 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01943_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01943');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01944
     * @tc.name WF_CB_01944_wifi_disableWifi
     * @tc.desc combo flow#18 var#6 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01944_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01944');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01945
     * @tc.name WF_CB_01945_wifi_disableWifi
     * @tc.desc combo flow#18 var#7 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01945_wifi_disableWifi', 0, async () => {
      await executeApiTestCaseById('WF_CB_01945');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01946
     * @tc.name WF_CB_01946_wifi_reassociate
     * @tc.desc combo flow#19 var#0 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01946_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01946');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01947
     * @tc.name WF_CB_01947_wifi_reassociate
     * @tc.desc combo flow#19 var#1 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01947_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01947');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01948
     * @tc.name WF_CB_01948_wifi_reassociate
     * @tc.desc combo flow#19 var#2 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01948_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01948');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01949
     * @tc.name WF_CB_01949_wifi_reassociate
     * @tc.desc combo flow#19 var#3 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01949_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01949');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01950
     * @tc.name WF_CB_01950_wifi_reassociate
     * @tc.desc combo flow#19 var#4 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01950_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01950');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01951
     * @tc.name WF_CB_01951_wifi_reassociate
     * @tc.desc combo flow#19 var#5 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01951_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01951');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01952
     * @tc.name WF_CB_01952_wifi_reassociate
     * @tc.desc combo flow#19 var#6 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01952_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01952');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01953
     * @tc.name WF_CB_01953_wifi_reassociate
     * @tc.desc combo flow#19 var#7 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01953_wifi_reassociate', 0, async () => {
      await executeApiTestCaseById('WF_CB_01953');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01954
     * @tc.name WF_CB_01954_wifi_removeDevice
     * @tc.desc combo flow#20 var#0 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01954_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01954');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01955
     * @tc.name WF_CB_01955_wifi_removeDevice
     * @tc.desc combo flow#20 var#1 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01955_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01955');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01956
     * @tc.name WF_CB_01956_wifi_removeDevice
     * @tc.desc combo flow#20 var#2 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01956_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01956');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01957
     * @tc.name WF_CB_01957_wifi_removeDevice
     * @tc.desc combo flow#20 var#3 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01957_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01957');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01958
     * @tc.name WF_CB_01958_wifi_removeDevice
     * @tc.desc combo flow#20 var#4 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01958_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01958');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01959
     * @tc.name WF_CB_01959_wifi_removeDevice
     * @tc.desc combo flow#20 var#5 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01959_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01959');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01960
     * @tc.name WF_CB_01960_wifi_removeDevice
     * @tc.desc combo flow#20 var#6 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01960_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01960');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01961
     * @tc.name WF_CB_01961_wifi_removeDevice
     * @tc.desc combo flow#20 var#7 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01961_wifi_removeDevice', 0, async () => {
      await executeApiTestCaseById('WF_CB_01961');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01962
     * @tc.name WF_CB_01962_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#0 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01962_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01962');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01963
     * @tc.name WF_CB_01963_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#1 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01963_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01963');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01964
     * @tc.name WF_CB_01964_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#2 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01964_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01964');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01965
     * @tc.name WF_CB_01965_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#3 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01965_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01965');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01966
     * @tc.name WF_CB_01966_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#4 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01966_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01966');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01967
     * @tc.name WF_CB_01967_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#5 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01967_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01967');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01968
     * @tc.name WF_CB_01968_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#6 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01968_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01968');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WF_CB_01969
     * @tc.name WF_CB_01969_wifi_removeAllNetwork
     * @tc.desc combo flow#21 var#7 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WF_CB_01969_wifi_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WF_CB_01969');
    });

}
