/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 自动生成，请勿手改 */
import { it } from '@ohos/hypium';
import { executeApiTestCaseById } from '../ApiTestRunner';

/** 注册 Api_Combination_Coverage 分片 part02（须在 describe 内调用） */
export function register_combo_part02(): void {
    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00900
     * @tc.name WM_CB_00900_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#4 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00900_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00900');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00901
     * @tc.name WM_CB_00901_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#5 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00901_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00901');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00902
     * @tc.name WM_CB_00902_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#6 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00902_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00902');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00903
     * @tc.name WM_CB_00903_wifiManager_getHotspotBlockList
     * @tc.desc combo flow#12 var#7 -> getHotspotBlockList
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00903_wifiManager_getHotspotBlockList', 0, async () => {
      await executeApiTestCaseById('WM_CB_00903');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00904
     * @tc.name WM_CB_00904_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#0 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00904_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00904');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00905
     * @tc.name WM_CB_00905_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#1 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00905_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00905');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00906
     * @tc.name WM_CB_00906_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#2 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00906_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00906');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00907
     * @tc.name WM_CB_00907_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#3 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00907_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00907');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00908
     * @tc.name WM_CB_00908_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#4 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00908_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00908');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00909
     * @tc.name WM_CB_00909_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#5 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00909_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00909');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00910
     * @tc.name WM_CB_00910_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#6 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00910_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00910');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00911
     * @tc.name WM_CB_00911_wifiManager_isHotspotActive
     * @tc.desc combo flow#13 var#7 -> isHotspotActive
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00911_wifiManager_isHotspotActive', 0, async () => {
      await executeApiTestCaseById('WM_CB_00911');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00912
     * @tc.name WM_CB_00912_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#0 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00912_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00912');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00913
     * @tc.name WM_CB_00913_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#1 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00913_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00913');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00914
     * @tc.name WM_CB_00914_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#2 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00914_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00914');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00915
     * @tc.name WM_CB_00915_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#3 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00915_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00915');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00916
     * @tc.name WM_CB_00916_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#4 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00916_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00916');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00917
     * @tc.name WM_CB_00917_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#5 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00917_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00917');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00918
     * @tc.name WM_CB_00918_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#6 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00918_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00918');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00919
     * @tc.name WM_CB_00919_wifiManager_stopDiscoverDevices
     * @tc.desc combo flow#14 var#7 -> stopDiscoverDevices
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00919_wifiManager_stopDiscoverDevices', 0, async () => {
      await executeApiTestCaseById('WM_CB_00919');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00920
     * @tc.name WM_CB_00920_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#0 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00920_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00920');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00921
     * @tc.name WM_CB_00921_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#1 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00921_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00921');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00922
     * @tc.name WM_CB_00922_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#2 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00922_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00922');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00923
     * @tc.name WM_CB_00923_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#3 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00923_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00923');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00924
     * @tc.name WM_CB_00924_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#4 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00924_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00924');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00925
     * @tc.name WM_CB_00925_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#5 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00925_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00925');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00926
     * @tc.name WM_CB_00926_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#6 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00926_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00926');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00927
     * @tc.name WM_CB_00927_wifiManager_getP2pLinkedInfo
     * @tc.desc combo flow#15 var#7 -> getP2pLinkedInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00927_wifiManager_getP2pLinkedInfo', 0, async () => {
      await executeApiTestCaseById('WM_CB_00927');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00928
     * @tc.name WM_CB_00928_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#0 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00928_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00928');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00929
     * @tc.name WM_CB_00929_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#1 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00929_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00929');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00930
     * @tc.name WM_CB_00930_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#2 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00930_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00930');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00931
     * @tc.name WM_CB_00931_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#3 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00931_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00931');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00932
     * @tc.name WM_CB_00932_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#4 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00932_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00932');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00933
     * @tc.name WM_CB_00933_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#5 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00933_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00933');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00934
     * @tc.name WM_CB_00934_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#6 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00934_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00934');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00935
     * @tc.name WM_CB_00935_wifiManager_getCurrentGroup
     * @tc.desc combo flow#16 var#7 -> getCurrentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00935_wifiManager_getCurrentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00935');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00936
     * @tc.name WM_CB_00936_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#0 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00936_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00936');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00937
     * @tc.name WM_CB_00937_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#1 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00937_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00937');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00938
     * @tc.name WM_CB_00938_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#2 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00938_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00938');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00939
     * @tc.name WM_CB_00939_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#3 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00939_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00939');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00940
     * @tc.name WM_CB_00940_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#4 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00940_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00940');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00941
     * @tc.name WM_CB_00941_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#5 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00941_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00941');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00942
     * @tc.name WM_CB_00942_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#6 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00942_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00942');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00943
     * @tc.name WM_CB_00943_wifiManager_deletePersistentGroup
     * @tc.desc combo flow#17 var#7 -> deletePersistentGroup
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00943_wifiManager_deletePersistentGroup', 0, async () => {
      await executeApiTestCaseById('WM_CB_00943');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00944
     * @tc.name WM_CB_00944_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#0 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00944_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00944');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00945
     * @tc.name WM_CB_00945_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#1 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00945_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00945');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00946
     * @tc.name WM_CB_00946_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#2 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00946_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00946');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00947
     * @tc.name WM_CB_00947_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#3 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00947_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00947');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00948
     * @tc.name WM_CB_00948_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#4 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00948_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00948');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00949
     * @tc.name WM_CB_00949_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#5 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00949_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00949');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00950
     * @tc.name WM_CB_00950_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#6 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00950_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00950');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00951
     * @tc.name WM_CB_00951_wifiManager_disableWifi
     * @tc.desc combo flow#18 var#7 -> disableWifi
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00951_wifiManager_disableWifi', 0, async () => {
      await executeApiTestCaseById('WM_CB_00951');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00952
     * @tc.name WM_CB_00952_wifiManager_reassociate
     * @tc.desc combo flow#19 var#0 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00952_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00952');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00953
     * @tc.name WM_CB_00953_wifiManager_reassociate
     * @tc.desc combo flow#19 var#1 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00953_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00953');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00954
     * @tc.name WM_CB_00954_wifiManager_reassociate
     * @tc.desc combo flow#19 var#2 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00954_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00954');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00955
     * @tc.name WM_CB_00955_wifiManager_reassociate
     * @tc.desc combo flow#19 var#3 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00955_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00955');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00956
     * @tc.name WM_CB_00956_wifiManager_reassociate
     * @tc.desc combo flow#19 var#4 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00956_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00956');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00957
     * @tc.name WM_CB_00957_wifiManager_reassociate
     * @tc.desc combo flow#19 var#5 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00957_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00957');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00958
     * @tc.name WM_CB_00958_wifiManager_reassociate
     * @tc.desc combo flow#19 var#6 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00958_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00958');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00959
     * @tc.name WM_CB_00959_wifiManager_reassociate
     * @tc.desc combo flow#19 var#7 -> reassociate
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00959_wifiManager_reassociate', 0, async () => {
      await executeApiTestCaseById('WM_CB_00959');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00960
     * @tc.name WM_CB_00960_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#0 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00960_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00960');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00961
     * @tc.name WM_CB_00961_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#1 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00961_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00961');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00962
     * @tc.name WM_CB_00962_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#2 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00962_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00962');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00963
     * @tc.name WM_CB_00963_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#3 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00963_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00963');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00964
     * @tc.name WM_CB_00964_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#4 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00964_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00964');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00965
     * @tc.name WM_CB_00965_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#5 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00965_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00965');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00966
     * @tc.name WM_CB_00966_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#6 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00966_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00966');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00967
     * @tc.name WM_CB_00967_wifiManager_removeDevice
     * @tc.desc combo flow#20 var#7 -> removeDevice
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00967_wifiManager_removeDevice', 0, async () => {
      await executeApiTestCaseById('WM_CB_00967');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00968
     * @tc.name WM_CB_00968_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#0 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00968_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00968');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00969
     * @tc.name WM_CB_00969_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#1 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00969_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00969');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00970
     * @tc.name WM_CB_00970_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#2 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00970_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00970');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00971
     * @tc.name WM_CB_00971_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#3 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00971_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00971');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00972
     * @tc.name WM_CB_00972_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#4 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00972_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00972');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00973
     * @tc.name WM_CB_00973_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#5 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00973_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00973');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00974
     * @tc.name WM_CB_00974_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#6 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00974_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00974');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_CB_00975
     * @tc.name WM_CB_00975_wifiManager_removeAllNetwork
     * @tc.desc combo flow#21 var#7 -> removeAllNetwork
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_CB_00975_wifiManager_removeAllNetwork', 0, async () => {
      await executeApiTestCaseById('WM_CB_00975');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01508
     * @tc.name WM_X_01508_wifiManager_getCountryCode
     * @tc.desc short_combo isWifiActive->getCountryCode
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01508_wifiManager_getCountryCode', 0, async () => {
      await executeApiTestCaseById('WM_X_01508');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01509
     * @tc.name WM_X_01509_wifiManager_getIpInfo
     * @tc.desc short_combo isWifiActive->getIpInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01509_wifiManager_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WM_X_01509');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01510
     * @tc.name WM_X_01510_wifiManager_getDeviceMacAddress
     * @tc.desc short_combo isWifiActive->getDeviceMacAddress
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01510_wifiManager_getDeviceMacAddress', 0, async () => {
      await executeApiTestCaseById('WM_X_01510');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01511
     * @tc.name WM_X_01511_wifiManager_getSupportedFeatures
     * @tc.desc short_combo isWifiActive->getSupportedFeatures
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01511_wifiManager_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WM_X_01511');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01512
     * @tc.name WM_X_01512_wifiManager_isConnected
     * @tc.desc short_combo isWifiActive->isConnected
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01512_wifiManager_isConnected', 0, async () => {
      await executeApiTestCaseById('WM_X_01512');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01513
     * @tc.name WM_X_01513_wifiManager_getWifiDetailState
     * @tc.desc short_combo isWifiActive->getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01513_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_X_01513');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01514
     * @tc.name WM_X_01514_wifiManager_getIpInfo
     * @tc.desc short_combo getCountryCode->getIpInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01514_wifiManager_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WM_X_01514');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01515
     * @tc.name WM_X_01515_wifiManager_getDeviceMacAddress
     * @tc.desc short_combo getCountryCode->getDeviceMacAddress
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01515_wifiManager_getDeviceMacAddress', 0, async () => {
      await executeApiTestCaseById('WM_X_01515');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01516
     * @tc.name WM_X_01516_wifiManager_getSupportedFeatures
     * @tc.desc short_combo getCountryCode->getSupportedFeatures
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01516_wifiManager_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WM_X_01516');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01517
     * @tc.name WM_X_01517_wifiManager_isConnected
     * @tc.desc short_combo getCountryCode->isConnected
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01517_wifiManager_isConnected', 0, async () => {
      await executeApiTestCaseById('WM_X_01517');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01518
     * @tc.name WM_X_01518_wifiManager_getWifiDetailState
     * @tc.desc short_combo getCountryCode->getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01518_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_X_01518');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01519
     * @tc.name WM_X_01519_wifiManager_getDeviceMacAddress
     * @tc.desc short_combo getIpInfo->getDeviceMacAddress
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01519_wifiManager_getDeviceMacAddress', 0, async () => {
      await executeApiTestCaseById('WM_X_01519');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01520
     * @tc.name WM_X_01520_wifiManager_getSupportedFeatures
     * @tc.desc short_combo getIpInfo->getSupportedFeatures
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01520_wifiManager_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WM_X_01520');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01521
     * @tc.name WM_X_01521_wifiManager_isConnected
     * @tc.desc short_combo getIpInfo->isConnected
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01521_wifiManager_isConnected', 0, async () => {
      await executeApiTestCaseById('WM_X_01521');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01522
     * @tc.name WM_X_01522_wifiManager_getWifiDetailState
     * @tc.desc short_combo getIpInfo->getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01522_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_X_01522');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01523
     * @tc.name WM_X_01523_wifiManager_getSupportedFeatures
     * @tc.desc short_combo getDeviceMacAddress->getSupportedFeatures
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01523_wifiManager_getSupportedFeatures', 0, async () => {
      await executeApiTestCaseById('WM_X_01523');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01524
     * @tc.name WM_X_01524_wifiManager_isConnected
     * @tc.desc short_combo getDeviceMacAddress->isConnected
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01524_wifiManager_isConnected', 0, async () => {
      await executeApiTestCaseById('WM_X_01524');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01525
     * @tc.name WM_X_01525_wifiManager_getWifiDetailState
     * @tc.desc short_combo getDeviceMacAddress->getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01525_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_X_01525');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01526
     * @tc.name WM_X_01526_wifiManager_isConnected
     * @tc.desc short_combo getSupportedFeatures->isConnected
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01526_wifiManager_isConnected', 0, async () => {
      await executeApiTestCaseById('WM_X_01526');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01527
     * @tc.name WM_X_01527_wifiManager_getWifiDetailState
     * @tc.desc short_combo getSupportedFeatures->getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01527_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_X_01527');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01528
     * @tc.name WM_X_01528_wifiManager_getWifiDetailState
     * @tc.desc short_combo isConnected->getWifiDetailState
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01528_wifiManager_getWifiDetailState', 0, async () => {
      await executeApiTestCaseById('WM_X_01528');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01529
     * @tc.name WM_X_01529_wifiManager_getIpInfo
     * @tc.desc triple_combo isWifiActive->getCountryCode->getIpInfo
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01529_wifiManager_getIpInfo', 0, async () => {
      await executeApiTestCaseById('WM_X_01529');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01530
     * @tc.name WM_X_01530_wifiManager_getDeviceMacAddress
     * @tc.desc triple_combo isWifiActive->getCountryCode->getDeviceMacAddress
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01530_wifiManager_getDeviceMacAddress', 0, async () => {
      await executeApiTestCaseById('WM_X_01530');
    });

    /**
     * @tc.number SUB_WIFI_CONNECTIVITY_API_WM_X_01531
     * @tc.name WM_X_01531_wifiManager_isConnected
     * @tc.desc triple_combo isWifiActive->getCountryCode->isConnected
     * @tc.size LargeTest
     * @tc.type Function
     * @tc.level Level 3
     */
    it('WM_X_01531_wifiManager_isConnected', 0, async () => {
      await executeApiTestCaseById('WM_X_01531');
    });

}
