/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class LogData {
  TAG = 'WIFI_Test'
  //wifi
  testEnableWifi_StartLog = "testEnableWifi Start----------"
  testEnableWifi_EndLog = "testEnableWifi End----------"
  testDisableWifi_StartLog = "testDisableWifi Start----------"
  testDisableWifi_EndLog = "testDisableWifi End----------"
  testIsWifiActive_StartLog = "testIsWifiActive Start----------"
  testIsWifiActive_EndLog = "testDisableWifi End----------"
  testScan_StartLog = "testScan Start----------"
  testScan_EndLog = "testScan End----------"
  testForcibleScan_StartLog = "testForcibleScan Start----------"
  testForcibleScan_EndLog = "testForcibleScan End----------"
  testGetScanInfosPromise_StartLog = "testGetScanInfosPromise Start----------"
  testGetScanInfosPromise_EndLog = "testGetScanInfosPromise End----------"
  testGetScanInfosPromise_successfulLog = "getScanInfos promise successful"
  testGetScanInfos_infoLog = "wifi received scan info: "
  testGetScanInfosCallback_StartLog = "testGetScanInfosCallback Start----------"
  testGetScanInfosCallback_EndLog = "testGetScanInfosCallback End----------"
  testGetScanInfosCallback_successfulLog = "getScanInfos callback successful"
  testAddDeviceConfigPromise_StartLog = "testAddDeviceConfigPromise Start----------"
  testAddDeviceConfigPromise_EndLog = "testAddDeviceConfigPromise End----------"
  testAddDeviceConfigPromise_successfulLog = "addDeviceConfig promise successful"
  testAddDeviceConfigLog = "addDeviceConfig: "
  testAddDeviceConfigCallback_StartLog = "testAddDeviceConfigCallback Start----------"
  testAddDeviceConfigCallback_EndLog = "testAddDeviceConfigCallback End----------"
  testAddDeviceConfigCallback_successfulLog = "addDeviceConfig Callback successful"
  testAddUntrustedConfigPromise_StartLog = "testAddUntrustedConfigPromise Start----------"
  testAddUntrustedConfigPromise_EndLog = "testAddUntrustedConfigPromise End----------"
  testAddUntrustedConfigPromise_successfulLog = "addUntrustedConfig promise successful"
  testAddUntrustedConfigLog = "addUntrustedConfig: "
  testAddUntrustedConfigCallback_StartLog = "testAddUntrustedConfigCallback Start----------"
  testAddUntrustedConfigCallback_EndLog = "testAddUntrustedConfigCallback End----------"
  testAddUntrustedConfigCallback_successfulLog = "addUntrustedConfig Callback successful"
  testRemoveUntrustedConfigPromise_StartLog = "testRemoveUntrustedConfigPromise Start----------"
  testRemoveUntrustedConfigPromise_EndLog = "testRemoveUntrustedConfigPromise End----------"
  testRemoveUntrustedConfigPromise_successfulLog = "removeUntrustedConfig promise successful"
  testRemoveUntrustedConfigLog = "removeUntrustedConfig: "
  testRemoveUntrustedConfigCallback_StartLog = "testRemoveUntrustedConfigCallback Start----------"
  testRemoveUntrustedConfigCallback_EndLog = "testRemoveUntrustedConfigCallback End----------"
  testRemoveUntrustedConfigCallback_successfulLog = "removeUntrustedConfig Callback successful"
  testConnectToNetwork_StartLog = "testConnectToNetwork Start----------"
  testConnectToNetwork_EndLog = "testConnectToNetwork End----------"
  testConnectToDevice_StartLog = "testConnectToDevice Start----------"
  testConnectToDevice_EndLog = "testConnectToDevice End----------"
  testDisconnect_StartLog = "testDisconnect Start----------"
  testDisconnect_EndLog = "testDisconnect End----------"
  testGetSignalLevel_StartLog = "testGetSignalLevel Start----------"
  testGetSignalLevel_EndLog = "testGetSignalLevel End----------"
  testGetLinkedInfoPromise_StartLog = "testGetLinkedInfoPromise Start----------"
  testGetLinkedInfoPromise_EndLog = "testGetLinkedInfoPromise End----------"
  testGetLinkedInfoPromise_successfulLog = "getLinkedInfoPromise test successful"
  testGetLinkedInfoCallback_StartLog = "testGetLinkedInfoCallback Start----------"
  testGetLinkedInfoCallback_EndLog = "testGetLinkedInfoCallback End----------"
  testGetLinkedInfoCallback_successfulLog = "getLinkedInfoCallback test successful"
  testIsConnected_StartLog = "testIsConnected Start----------"
  testIsConnected_EndLog = "testIsConnected End----------"
  testGetSupportedFeatures_StartLog = "testGetSupportedFeatures Start----------"
  testGetSupportedFeatures_EndLog = "testGetSupportedFeatures End----------"
  testIsFeatureSupported_StartLog = "testIsFeatureSupported Start----------"
  testIsFeatureSupported_EndLog = "testIsFeatureSupported End----------"
  testGetDeviceMacAddress_StartLog = "testGetDeviceMacAddress Start----------"
  testGetDeviceMacAddress_EndLog = "testGetDeviceMacAddress End----------"
  testGetIpInfo_StartLog = "testGetIpInfo Start----------"
  testGetIpInfo_EndLog = "testGetIpInfo End----------"
  testGetCountryCode_StartLog = "testGetCountryCode Start----------"
  testGetCountryCode_EndLog = "testGetCountryCode End----------"
  testReassociate_StartLog = "testReassociate Start----------"
  testReassociate_EndLog = "testReassociate End----------"
  testReConnect_StartLog = "testReConnect Start----------"
  testReConnect_EndLog = "testReConnect End----------"
  testGetDeviceConfigs_StartLog = "testGetDeviceConfigs Start----------"
  testGetDeviceConfigs_EndLog = "testGetDeviceConfigs End----------"
  testUpdateNetwork_StartLog = "testUpdateNetwork Start----------"
  testUpdateNetwork_EndLog = "testUpdateNetwork End----------"
  testDisableNetwork_StartLog = "testDisableNetwork Start----------"
  testDisableNetwork_EndLog = "testDisableNetwork End----------"
  testRemoveAllNetwork_StartLog = "testRemoveAllNetwork Start----------"
  testRemoveAllNetwork_EndLog = "testRemoveAllNetwork End----------"
  testRemoveDevice_StartLog = "testRemoveDevice Start----------"
  testRemoveDevice_EndLog = "testRemoveDevice End----------"
  testOnWifiStateChange_StartLog = "testOnWifiStateChange Start----------"
  testOnWifiStateChange_EndLog = "testOnWifiStateChange End----------"
  testOnWifiConnectionChange_StartLog = "testOnWifiConnectionChange Start----------"
  testOnWifiConnectionChange_EndLog = "testOnWifiConnectionChange End----------"
  testOnWifiScanStateChange_StartLog = "testOnWifiConnectionChange Start----------"
  testOnWifiScanStateChange_EndLog = "testOnWifiConnectionChange End----------"
  testOnWifiRssiChange_StartLog = "testOnWifiRssiChange Start----------"
  testOnWifiRssiChange_EndLog = "testOnWifiRssiChange End----------"
  testOnStreamChange_StartLog = "testOnStreamChange Start----------"
  testOnStreamChange_EndLog = "testOnStreamChange End----------"
  //hotspot
  testEnableHotspot_StartLog = "testEnableHotspot start--------------"
  testEnableHotspot_EndLog = "testEnableHotspot End--------------"
  testDisableHotspot_StartLog = "testDisableHotspot start--------------"
  testDisableHotspot_EndLog = "testDisableHotspot End--------------"
  testIsHotspotDualBandSupported_StartLog = "testIsHotspotDualBandSupported start--------------"
  testIsHotspotDualBandSupported_EndLog = "testIsHotspotDualBandSupported End--------------"
  testIsHostActive_StartLog = "testIsHostActive start--------------"
  testIsHostActive_EndLog = "testIsHostActive End--------------"
  testSetHotspotConfig_StartLog = "testSetHotspotConfig start--------------"
  testSetHotspotConfig_EndLog = "testSetHotspotConfig End--------------"
  testGetHotspotConfig_StartLog = "testGetHotspotConfig start--------------"
  testGetHotspotConfig_EndLog = "testGetHotspotConfig End--------------"
  testGetStations_StartLog = "testGetStations start--------------"
  testGetStations_EndLog = "testGetStations End--------------"
  testOnHotspotStateChange_StartLog = "testOnHotspotStateChange start--------------"
  testOnHotspotStateChange_EndLog = "testOnHotspotStateChange End--------------"
  testOnHotspotStaJoin_StartLog = "testOnHotspotStaJoin start--------------"
  testOnHotspotStaJoin_EndLog = "testOnHotspotStaJoin End--------------"
  testOnHotspotStaLeave_StartLog = "testOnHotspotStaLeave start--------------"
  testOnHotspotStaLeave_EndLog = "testOnHotspotStaLeave End--------------"
  //p2p
  testGetP2pLinkedInfoPromise_StartLog = "testGetP2pLinkedInfoPromise Start----------"
  testGetP2pLinkedInfoPromise_EndLog = "testGetP2pLinkedInfoPromise End----------"
  getP2pLinkedInfoPromise_successfulLog = "getP2pLinkedInfoPromise successful"
  testGetP2pLinkedInfoCallback_StartLog = "testGetP2pLinkedInfoCallback Start----------"
  testGetP2pLinkedInfoCallback_EndLog = "testGetP2pLinkedInfoCallback End----------"
  getP2pLinkedInfoCallback_successfulLog = "getP2pLinkedInfoCallback successful "
  testGetCurrentGroupPromise_StartLog = "testGetCurrentGroupPromise Start----------"
  testGetCurrentGroupPromise_EndLog = "testGetCurrentGroupPromise End----------"
  testGetCurrentGroupPromise_successfulLog = "getCurrentGroupPromise successful"
  testGetCurrentGroupCallback_StartLog = "testGetCurrentGroupCallback Start----------"
  testGetCurrentGroupCallback_EndLog = "testGetCurrentGroupCallback End----------"
  getCurrentGroupCallback_successfulLog = "getCurrentGroupCallback successful"
  testGetP2pPeerDevicesPromise_StartLog = "testGetP2pPeerDevicesPromise Start----------"
  testGetP2pPeerDevicesPromise_EndLog = "testGetP2pPeerDevicesPromise End----------"
  getP2pPeerDevicesPromise_successfulLog = "getP2pPeerDevicesPromise successful"
  testGetP2pPeerDevicesCallback_StartLog = "testGetP2pPeerDevicesCallback Start----------"
  testGetP2pPeerDevicesCallback_EndLog = "testGetP2pPeerDevicesCallback End----------"
  getP2pPeerDevicesCallback_successfulLog = "getP2pPeerDevicesCallback successful"
  testCreateGroup_StartLog = "testCreateGroup Start----------"
  testCreateGroup_EndLog = "testCreateGroup End----------"
  testRemoveGroup_StartLog = "testRemoveGroup Start----------"
  testRemoveGroup_EndLog = "testRemoveGroup End----------"
  testP2pConnect_StartLog = "testP2pConnect Start----------"
  testP2pConnect_EndLog = "testP2pConnect End----------"
  testP2pCancelConnect_StartLog = "testP2pCancelConnect Start----------"
  testP2pCancelConnect_EndLog = "testP2pCancelConnect End----------"
  testStartDiscoverDevices_StartLog = "testStartDiscoverDevices Start----------"
  testStartDiscoverDevices_EndLog = "testStartDiscoverDevices End----------"
  testStopDiscoverDevices_StartLog = "testStopDiscoverDevices Start----------"
  testStopDiscoverDevices_EndLog = "testStopDiscoverDevices End----------"
  testDeletePersistentGroup_StartLog = "testDeletePersistentGroup Start----------"
  testDeletePersistentGroup_EndLog = "testDeletePersistentGroup End----------"
  testSetDeviceName_StartLog = "testSetDeviceName Start----------"
  testSetDeviceName_EndLog = "testSetDeviceName End----------"
  testOnP2pStateChange_StartLog = "testOnP2pStateChange Start----------"
  testOnP2pStateChange_EndLog = "testOnP2pStateChange End----------"
  testOnP2pConnectionChange_StartLog = "testOnP2pConnectionChange Start----------"
  testOnP2pConnectionChange_EndLog = "testOnP2pConnectionChange End----------"
  testOnP2pDeviceChange_StartLog = "testOnP2pDeviceChange Start----------"
  testOnP2pDeviceChange_EndLog = "testOnP2pDeviceChange End----------"
  testOnP2pPeerDeviceChange_StartLog = "testOnP2pPeerDeviceChange Start----------"
  testOnP2pPeerDeviceChange_EndLog = "testOnP2pPeerDeviceChange End----------"
  testOnP2pPersistentGroupChange_StartLog = "testOnP2pPersistentGroupChange Start----------"
  testOnP2pPersistentGroupChange_EndLog = "testOnP2pPersistentGroupChange End----------"
  testOnP2pDiscoveryChange_StartLog = "testOnP2pDiscoveryChange Start----------"
  testOnP2pDiscoveryChange_EndLog = "testOnP2pDiscoveryChange End----------"
}

let logData = new LogData();

export default logData as LogData;