/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  describe,
  beforeAll,
  beforeEach,
  afterEach,
  afterAll,
  it,
  expect
} from '@ohos/hypium';

export default function abilityTest(): void {
  describe('ActsAbilityTest', () => {
    beforeAll(() => {
    });
    beforeEach(() => {
    });
    afterEach(() => {
    });
    afterAll(() => {
    });

    /**
     * @tc.number SUB_WIFI_TESTAPP_ABILITY_0000
     * @tc.name ActsAbilityTest_smoke
     * @tc.desc Ability test suite smoke placeholder
     * @tc.size MediumTest
     * @tc.type Function
     * @tc.level Level 0
     */
    it('ActsAbilityTest_smoke', 0, () => {
      expect(true).assertTrue();
    });
  });
}
