/**
 * Copyright (c) 2022 Shenzhen Kaihong Digital Industry Development Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/** 本文件由 generate_ohostest_api_catalog.py 自动生成，请勿手改 */
import { ApiTestCase } from './ApiTestTypes';
import { APITESTCATALOG_PART01 } from './catalog/ApiTestCatalog.part01';
import { APITESTCATALOG_PART02 } from './catalog/ApiTestCatalog.part02';
import { APITESTCATALOG_PART03 } from './catalog/ApiTestCatalog.part03';
import { APITESTCATALOG_PART04 } from './catalog/ApiTestCatalog.part04';
import { APITESTCATALOG_PART05 } from './catalog/ApiTestCatalog.part05';
import { APITESTCATALOG_PART06 } from './catalog/ApiTestCatalog.part06';
import { APITESTCATALOG_PART07 } from './catalog/ApiTestCatalog.part07';
import { APITESTCATALOG_PART08 } from './catalog/ApiTestCatalog.part08';
import { APITESTCATALOG_PART09 } from './catalog/ApiTestCatalog.part09';
import { APITESTCATALOG_PART10 } from './catalog/ApiTestCatalog.part10';
import { APITESTCATALOG_PART11 } from './catalog/ApiTestCatalog.part11';
import { APITESTCATALOG_PART12 } from './catalog/ApiTestCatalog.part12';
import { APITESTCATALOG_PART13 } from './catalog/ApiTestCatalog.part13';
import { APITESTCATALOG_PART14 } from './catalog/ApiTestCatalog.part14';
import { APITESTCATALOG_PART15 } from './catalog/ApiTestCatalog.part15';
import { APITESTCATALOG_PART16 } from './catalog/ApiTestCatalog.part16';
import { APITESTCATALOG_PART17 } from './catalog/ApiTestCatalog.part17';
import { APITESTCATALOG_PART18 } from './catalog/ApiTestCatalog.part18';
import { APITESTCATALOG_PART19 } from './catalog/ApiTestCatalog.part19';
import { APITESTCATALOG_PART20 } from './catalog/ApiTestCatalog.part20';
import { APITESTCATALOG_PART21 } from './catalog/ApiTestCatalog.part21';

export const API_TEST_CASE_COUNT: number = 2006;
export const API_TEST_CASES: ApiTestCase[] = [
  ...APITESTCATALOG_PART01,
  ...APITESTCATALOG_PART02,
  ...APITESTCATALOG_PART03,
  ...APITESTCATALOG_PART04,
  ...APITESTCATALOG_PART05,
  ...APITESTCATALOG_PART06,
  ...APITESTCATALOG_PART07,
  ...APITESTCATALOG_PART08,
  ...APITESTCATALOG_PART09,
  ...APITESTCATALOG_PART10,
  ...APITESTCATALOG_PART11,
  ...APITESTCATALOG_PART12,
  ...APITESTCATALOG_PART13,
  ...APITESTCATALOG_PART14,
  ...APITESTCATALOG_PART15,
  ...APITESTCATALOG_PART16,
  ...APITESTCATALOG_PART17,
  ...APITESTCATALOG_PART18,
  ...APITESTCATALOG_PART19,
  ...APITESTCATALOG_PART20,
  ...APITESTCATALOG_PART21
];
